### ISSUE TITLE
BUG: handle_reveal did not handle the dir parameter passed to execute

### ISSUE THREAD

**Issue by Kaiser-Yang** [nvim-neo-tree/neo-tree.nvim#1641] opened 2024-12-31 11:53 UTC
### Did you check docs and existing issues?

- [X] I have read all the docs.
- [X] I have searched the existing issues.
- [X] I have searched the existing discussions.

### Neovim Version (nvim -v)

0.10.1

### Operating System / Version

WSL2 + Ubuntu 22.04 LTS

### Describe the Bug

The execute function, with parameter reveal, will call handle_reveal:

![image](https://github.com/user-attachments/assets/13899225-62bc-4da5-bc65-4b352b3d8c58)

In handle_reveal function, it does not handle the args.dir passed by execute({ dir = 'xxx'}). 

![image](https://github.com/user-attachments/assets/5a0bb441-8118-4cf7-a1d0-3740a59bb8e8)

### Screenshots, Traceback

It should check if the args.dir is parent of the reveal_file when args.dir is not nil, because args.dir means where we'll go. Therefore, when args.dir is reveal_file's parent, this means the reveal is legal, and we don't neet to let users confirm. Like the code below:

![image](https://github.com/user-attachments/assets/f0d3cfc2-4646-455f-9994-3e2171e7921b)

### Steps to Reproduce

None

### Expected Behavior

In handle_reveal, it should check if the args.dir is nil, whne nil use the reveal_file's path, like this below:

### Your Configuration

```Lua
None
```

**Comment by pynappo** [comment] 2024-12-31 12:06
dupe of https://github.com/nvim-neo-tree/neo-tree.nvim/issues/1500 (forgot to reopen it after the initial fix caused unintended errors). will fix asap.

**Closed by pynappo** 2024-12-31 12:06 UTC
Labels: bug

**Comment by alanoliveira** [comment] 2024-12-31 12:14
@pynappo , should I create a new PR with the fix?
