### ISSUE TITLE
BUG: <C-b> useless

### ISSUE THREAD

**Issue by cathaysia** [nvim-neo-tree/neo-tree.nvim#1524] opened 2024-07-16 01:44 UTC
### Did you check docs and existing issues?

- [X] I have read all the docs.
- [X] I have searched the existing issues.
- [X] I have searched the existing discussions.

### Neovim Version (nvim -v)

NVIM v0.10.0 Build type: Release LuaJIT 2.1.1713484068

### Operating System / Version

macos 14.5 (23F79)/Fedora 40

### Describe the Bug

<C-b> doesn't work on both linux and macos.

### Steps to Reproduce

1. open neovim-tree
2. press <C-f> then press <C-b>
3. <C-b> doesn't work.

### Expected Behavior

<C-b> should work

---- 

This issue exists for a long time. I locate the bad commit by git, find it should be 6e20108c4a8128782f534f5fe90c757b44212ef6

**Comment by cathaysia** [comment] 2024-07-16 01:51
After applay this patch, it works:

```diff
diff --git a/lua/neo-tree/defaults.lua b/lua/neo-tree/defaults.lua
index 733dcc0..1e5f278 100644
--- a/lua/neo-tree/defaults.lua
+++ b/lua/neo-tree/defaults.lua
@@ -28,7 +28,7 @@ local config = {
                        -- Anything before this will be used. The last items to be processed are the untracked files.
   },
   hide_root_node = false, -- Hide the root node.
-  retain_hidden_root_indent = false, -- IF the root node is hidden, keep the indentation anyhow.
+  retain_hidden_root_indent = false, -- IF the root node is hidden, keep the indentation anyhow.
                                      -- This is needed if you use expanders because they render in the indent.
   log_level = "info", -- "trace", "debug", "info", "warn", "error", "fatal"
   log_to_file = false, -- true, false, "/path/to/file.log", use :NeoTreeLogs to show the file
@@ -211,8 +211,8 @@ local config = {
     },
     name = {
       trailing_slash = false,
-      highlight_opened_files = false, -- Requires `enable_opened_markers = true`.
-                                      -- Take values in { false (no highlight), true (only loaded),
+      highlight_opened_files = false, -- Requires `enable_opened_markers = true`.
+                                      -- Take values in { false (no highlight), true (only loaded),
                                       -- "all" (both loaded and unloaded)}. For more information,
                                       -- see the `show_unloaded` config of the `buffers` source.
       use_git_status_colors = true,
@@ -368,8 +368,8 @@ local config = {
       -- ["<cr>"] = { "open", config = { expand_nested_files = true } }, -- expand nested file takes precedence
       ["<esc>"] = "cancel", -- close preview or floating neo-tree window
       ["P"] = { "toggle_preview", config = { use_float = true, use_image_nvim = false } },
-      ["<C-f>"] = { "scroll_preview", config = {direction = -10} },
-      ["<C-b>"] = { "scroll_preview", config = {direction = 10} },
+      -- ["<C-f>"] = { "scroll_preview", config = {direction = -10} },
+      -- ["<C-b>"] = { "scroll_preview", config = {direction = 10} },
       ["l"] = "focus_preview",
       ["S"] = "open_split",
       -- ["S"] = "split_with_window_picker",

```

**Comment by alethenorio** [comment] 2024-07-21 00:33
Was hit by this myself. Kept trying to figure out why my `<C-b>` toggle mapping would open the browser window and then wouldn't close it again. Debugging `:map` shows it is being set by neo-tree.

Is there any way to override this without having to wait for a PR with a fix?

**Comment by cathaysia** [comment] 2024-07-21 01:02
you can use 3.25 version

**Comment by miversen33** [comment] 2024-07-21 16:41
So a couple things here.
`<C-b>` isn't useless, the patch you applied tells you exactly what its doing. [Its bound to the `scroll_preview` function.](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/main/doc/neo-tree.txt#L227-L231) Specifically "scroll down" (that is why the direction is negative). Notice that the other part of your patch is removing the "scroll up" functionality of `scroll_preview`

Your "patch" is simply commenting out this behavior. Which I mean... Does work but is not how you solve this "problem".

If you don't like the behavior here, you can just set `<C-b>` to `noop`, or bind `<C-b>` to whatever functionality you want it to be. There is no need to apply a patch against the source code.

[This is actually called out in the helpdoc as well](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/main/doc/neo-tree.txt#L476-L491).

Try that out and see if it works for you.

A final note. This is not a bug

**Comment by cathaysia** [comment] 2024-07-22 01:47
yes, you're right. <C-d> scroll down, and <C-u> scroll up. This is not a bug. But it's possible only map these key when preview is visible?

**Comment by miversen33** [comment] 2024-07-24 02:55
That's a great question that I do not have an answer for. I will have to dig about a bit in the code to see if there is a way to bind the keymap only during previews.

That said, that does seem counterintuive, what would you expect to happen if you bind `<C-b>` to something and then both that thing _and_ the preview are available at the same time?

I would recommend simply remapping as suggested or using a different shortcut for what you are looking for. Optional binding seems like a big mess (**though it is worth checking the source to see if that is currently available**)

**Closed** 2024-07-24 03:09 UTC
Labels: wontfix
