### ISSUE TITLE
How can i use `project.nvim` to change root dir?

### ISSUE THREAD

**Issue by GreenSleeper** [nvim-neo-tree/neo-tree.nvim#784] opened 2023-03-03 13:30 UTC
I want to use `project.nvim` to decide the root dir of `neotree`, how should I do?

**Comment by cseickel** [comment] 2023-03-04 13:53
Neotree watches for current working directory changes by default. All you would need to do is to change the tab cwd (like with `tcd`), which is what the sidebars will be bound to.

If you want neo-tree to bind to the "global" cwd instead of "tab", you can change these settings:

https://github.com/nvim-neo-tree/neo-tree.nvim/blob/aec592bb1f0cf67f7e1123053d1eb17700aa9ed4/lua/neo-tree/defaults.lua#L378-L382

**Comment by sho-87** [comment] 2023-03-06 02:08
@cseickel I dont think thats working as intended, at least not in my case...

Im toggling neotree with:

```
map("n", "<leader>fn", "<cmd>Neotree reveal=true toggle=true<cr>")
```

Neotree config:

```
filesystem = {
bind_to_cwd = true,
cwd_target = {sidebar = "window"},
follow_current_file = true,
...}
```

which matches the scope I have set in project.nvim:

```
scope_chdir = "win"
```
when I `:pwd` I see that project has correctly set my window working directory. I can confirm this in other ways as well, for example, telescope find_files will start in my current window's wd. but when I toggle neotree it says the file is not in the wd and wants to change to immediate directory of the file:

![Screenshot 2023-03-05 174604](https://user-images.githubusercontent.com/5199715/223001516-449c8cd4-e697-4d25-8068-6b1c3147084d.png)

neotree seems to set its wd to the directory that I started nvim in, and not syncing with later changes in the wd. it either always asks for a manual wd change, or if I say no, will just open neotree in my nvim start directory. if I say yes, the expected thing happens, which is change wd to the files directory, which is not what I want

is neo-tree asking for a manual wd change because the file I want is not directly in the project root, but rather in a sub-directory? or is something else going on?

if relevant/useful:
OS: Windows
dotfile neo-tree: https://github.com/sho-87/dotfiles/blob/master/nvim/lua/plugins/modules/neo-tree.lua
dotfile project: https://github.com/sho-87/dotfiles/blob/master/nvim/lua/plugins/modules/project.lua

**Comment by GreenSleeper** [comment] 2023-03-06 03:21
> @cseickel I dont think thats working as intended, at least not in my case...
> 
> Im toggling neotree with:
> 
> ```
> map("n", "<leader>fn", "<cmd>Neotree reveal=true toggle=true<cr>")
> ```
> 
> Neotree config:
> 
> ```
> filesystem = {
> bind_to_cwd = true,
> cwd_target = {sidebar = "window"},
> follow_current_file = true,
> ...}
> ```
> 
> which matches the scope I have set in project.nvim:
> 
> ```
> scope_chdir = "win"
> ```
> 
> when I `:pwd` I see that project has correctly set my window working directory. I can confirm this in other ways as well, for example, telescope find_files will start in my current window's wd. but when I toggle neotree it says the file is not in the wd and wants to change to immediate directory of the file:
> 
> ![Screenshot 2023-03-05 174604](https://user-images.githubusercontent.com/5199715/223001516-449c8cd4-e697-4d25-8068-6b1c3147084d.png)
> 
> neotree seems to set its wd to the directory that I started nvim in, and not syncing with later changes in the wd. it either always asks for a manual wd change, or if I say no, will just open neotree in my nvim start directory. if I say yes, the expected thing happens, which is change wd to the files directory, which is not what I want
> 
> is neo-tree asking for a manual wd change because the file I want is not directly in the project root, but rather in a sub-directory? or is something else going on?
> 
> if relevant/useful: OS: Windows dotfile neo-tree: https://github.com/sho-87/dotfiles/blob/master/nvim/lua/plugins/modules/neo-tree.lua dotfile project: https://github.com/sho-87/dotfiles/blob/master/nvim/lua/plugins/modules/project.lua

Almost same here, `pwd` changed, but `neotree` root sometimes change with it and sometimes doesn't, I'm so confused.

**Comment by cseickel** [comment] 2023-03-06 03:35
Setting the scope to win/window doesn't make any sense at all. A sidebar is by definition not in the same window. Although this does not throw an error it really should:
```
cwd_target = {sidebar = "window"},
```

It only makes sense to set the sidebar to "tab" or "global". `project.nvim` will be set to "global" by default, so if you want to match you should set neo-tree like this:
```
cwd_target = {sidebar = "global"},
```

And then you do not need to change `scope_chdir` at all in `project.nvim`. Alternatively, you can set them both to "tab" and that would also work.

**Comment by sho-87** [comment] 2023-03-06 03:54
I guess I was expecting it to pull the wd from the window that called the toggle, but anyway

scope win is pretty useful because I sometimes have files open side by side from different projects. If I wanted to keep project to scope win, can I use something like a float neotree and set that scope to win also? I couldn't find any documentation about how floating scopes are set in neotree

**Comment by cseickel** [comment] 2023-03-06 04:02
Floats are treated as sidebars. I think what would make more sense for you is to use `position="current"` which opens within the window and will therefore naturally use the window local working directory. I personally use it that way 99% of the time instead of a sidebar or float.

**Comment by nhat-vo** [comment] 2023-04-09 09:24
Closing this issue as solved.

**Closed by nhat-vo** 2023-04-09 09:24 UTC
Labels: how-to
