### ISSUE TITLE
Splitting neo-tree.nvim windows results in malfunctioning

### ISSUE THREAD

**Issue by jaekyeom** [nvim-neo-tree/neo-tree.nvim#318] opened 2022-04-22 15:54 UTC
Hi,
I appreciate your effort put into developing and maintaining this great plugin.

I usually use file browser plugins (such as neo-tree.nvim) like normal buffers (i.e., `position = "current"`),
and one thing I noticed is that if I split a neo-tree.nvim window (which is what I often do with file browser plugins), only one of them works correctly.
After I use the working neo-tree.nvim window to open some file in the same window,
then I can "refresh" one of the remaining neo-tree.nvim windows and use it (whereas the rest still don't work).

I'm using the official `NVIM v0.7.0` binary on macOS, and using the latest version of neo-tree.nvim (`44310cf6dd0e57b747f0946976d17e0106c9e611`).
Could you please look into this issue to see if this can be fixed?

**Comment by cseickel** [comment] 2022-04-22 19:15
Interesting, I just haven't used it this way before. If I want a second neo-tree window, I would always issue a `edit .` command to create that new tree or split a normal file buffer and open the tree instead of just `split`ing the current neo-tree window.

I currently have the state of the tree bound to the window it was created in. For this to work, I should bind it to the buffer number instead. That's probably a more correct approach to be honest, and making this change might also fix a strange bug that I have been unable to recreate...

**Comment by cseickel** [comment] 2022-04-22 23:57
This should be fixed in the `main` branch. Can you try it out and let me know if it works as expected?

I should mention that by design the state of a tree is bound to the window. What I did was to create a new tree if you try to reuse a neo-tree buffer in a new window (which is what a straight `split` command would do.)

**Comment by jaekyeom** [comment] 2022-04-23 12:16
I think that's a reasonable workaround, and it works like a charm.
Thank you for the quick update!

**Comment by jaekyeom** [comment] 2022-04-24 08:50
@cseickel Unfortunately, I notice some new issue.
It seems that now neo-tree.nvim intercepts some non-neo-tree buffers, like [toggleterm](https://github.com/akinsho/toggleterm.nvim) buffers:

https://user-images.githubusercontent.com/6262727/164968278-b112a800-38ea-4012-9a9d-f44053f4bfe4.mov

The expected behavior here is, `:ToggleTerm` should open its terminal buffer at the bottom.

**Comment by cseickel** [comment] 2022-04-24 12:17
@jaekyeom That issue should be fixed now.

**Comment by jaekyeom** [comment] 2022-04-24 12:29
@cseickel It looks that the issue has been fixed, indeed. Thanks!

**Closed** 2022-04-24 13:14 UTC
Labels: bug, enhancement
