### ISSUE TITLE
Hijacking netrw mode: should not limited to fixed vsplit layout

### ISSUE THREAD

**Issue by wookayin** [nvim-neo-tree/neo-tree.nvim#121] opened 2022-02-03 20:52 UTC
This is similar to https://github.com/kyazdani42/nvim-tree.lua/issues/926.

When NeoTree is working as a standalone mode or hijacking netrw, it should work as if it were a normal directory buffer. However, it only works as a vertical splitted window on the left.

To Reproduce: `run :split .`

Expected behavior: This should open the directory buffer in a non-surprising way: open the directory window in the below or as a horizontally-split window.
Current behavior: It opens the nvim-tree window on the left.

Currently, `M.hijack_netrw` is doing the minimal implementation -- simply killing the netrw buffer and navigating neotree to the opened directory path. It instead should open in the window where netrw was at.

**Comment by cseickel** [comment] 2022-02-03 21:03
This is actually a duplicate of #23 , which is still in progress. When it is finished it will have the functionality you are looking for.

If you'd like to be an early tester, I believe this is fully working in the `netrw-style` branch. I'm holding it up because I want to get better testing in place first (#77), along with the enhanced command structure in #31.

The only downside to that branch is it is all or nothing, you either use it as a sidebar style or as split style, but you can have both yet. To enable the split style in that branch, set `filesystem.window.position = "split"` in your config.

**Comment by cseickel** [comment] 2022-02-07 04:12
Completed by #124

**Comment by wookayin** [comment] 2022-02-07 04:58
Thanks for implementing #124. `:NeoTreeShowInSplit` works like `edit .`, but as in the first message of the thread `vsplit .`, `split .` would call `:NeoTreeShow` rather than `:NeoTreeShowInSplit`. I guess this might be a simple follow-up fix for you?

**Comment by cseickel** [comment] 2022-02-07 12:35
I'm re-opening the issue because I mis-understood it the first time. It would be nice to simply react appropriately to `edit .`, `split .` and `vsplit .`. It almost works if you specify `"split"` as your default position, but it always closes the existing window which it shouldn't. I'll make this work correctly.

In the meantime, you can get the functionality you want with:
```
:vsplit | NeoTreeShowInSplit
```
and
```
:split | NeoTreeShowInSplit
```

**Comment by cseickel** [comment] 2022-02-08 01:36
This wasn't so difficult, it works now in **main**, it will be released soon. If your `filesystem.window.position = "split"`, then `edit .`, `vsplit .`, and `split .` all work as expected. If your position is anything else, all those commands just send the navigation aspect to the sidebar.

**Comment by wookayin** [comment] 2022-02-08 02:41
I gave it a try: when I do `vsplit .`, it make a new vertical split AND then neotree opens on the left. `split` would make a new horizontal split AND neotree opens on the left. Why would be I getting a different behavior? Does it require some config?

**Comment by cseickel** [comment] 2022-02-08 02:49
Yes, if you want this behavior you need to set your position to "split":

```lua
require("neo-tree").setup({
  filesystem = {
    window = {
      position = "split"
    }
  }
})
```

Does it work after you do that? Currently, there is no way to combine this behavior with the "left" sidebar because sidebar users probably would not want that. Let me know if you are interested in working in split mode only when hijacking netrw, it would not be difficult to add a flag to enable it.

**Comment by wookayin** [comment] 2022-02-08 03:15
That behavior sounds very weird and strange. NERDTree, for example, handles the both use cases seamlessly, so I believe there must be a good way. Let me later study how that can be achieved. Anyway thank you so much for implementing the new feature.

**Comment by cseickel** [comment] 2022-02-08 03:49
None of this is difficult to do, it's just that everyone has a different idea about how they expect it to behave and I'm trying to find a clean way of configuring this to accommodate everyone's expectations at once.

> Update: I feel like it's just all about how we define the command mapping -- for example, if the :NeoTreeShow(or some similar command) executes :topleft 20vsplit | NeoTree then it would achieve the current (default) behavior.

Not quite. The sidebar functionality is more complicated than just being a split that is a certain size. The sidebar needs to understand that is meant to be a sidebar and then take extra actions to lock it into place properly. There are also a lot of behavioral differences between a sidebar tree and a split window tree. For example, where to open a file and how to react to another buffer trying to take over it's window.

Of course, what you may be getting at is that we can handle this better if the commands were very explicit and didn't rely on configuration. That is true and @levouh actually started work on this in #31. The problem is that there are so many variations that we really need to redesign the command system from scratch, which will happen eventually. 

Meanwhile...

> That behavior sounds very weird and strange. NERDTree, for example, handles both use cases seamlessly and smoothly

If you would like to use it as a sidebar by default, but use it like netrw when `edit`ing a directory, while other people want the opposite, the solution is probably to add a some sort of configuration to choose between these options. I'm thinking we add an enumeration like this:

```lua
require("neo-tree").setup({
  hijack_netrw_behavior: "open_default" -- use whatever you have configured as the filesystem position. 
                                        -- "open_default" is the current behavior.
  hijack_netrw_behavior: "disabled" -- don't hijack anything
  hijack_netrw_behavior: "open_in_split" -- the behavior you are looking for, force it to "split" mode
                                         -- regardless of what your config says.
})
```

@nyngwang and @max107, since you were part of the initial design, please let me know if you have any thoughts on what the default should be and if my proposed configuration sounds like a good idea.

**Comment by wookayin** [comment] 2022-02-08 04:16
Thanks for the detailed context and information, and yes I understand this might be more complicated than it may seem.

> I'm thinking we add an enumeration like this:

The example (potential) configuration sounds too much and overly complicated. We already have too many open- or show-like commands, as pointed #31. I do not have a strong suggestion immediately about what the ideal set of commands would look like, but that was just my personal first impression.

By the way, I have another sugggestion: we would benefit from having a PR-based workflow to better test and discuss feature when it comes to a complex one that would need some decision and iteration. This way we would be able to reduce the risk of inevitable breaking changes.

**Comment by cseickel** [comment] 2022-02-08 12:38
> By the way, I have another sugggestion: we would benefit from having a PR-based workflow to better test and discuss feature when it comes to a complex one that would need some decision and iteration. This way we would be able to reduce the risk of inevitable breaking changes.

I absolutely agree. While we have a PR based workflow, I rarely use it for my own contributions. I think it would be a good idea to  slow down on pushing new enhancements and leave more time for discussion. I'll try using PRs and see if I get any engagement there.

**Comment by cseickel** [comment] 2022-02-08 17:39
Just to wrap this up so I can close the bugs, I added an undocumented experimental option to configure the netrw hijack bahavior. It's mostly as I described above but I put it under `filesystem` section instead:

```lua
require("neo-tree").setup({
  filesystem = {
    --hijack_netrw_behavior: "open_default" -- use whatever you have configured as the filesystem position. 
                                          -- "open_default" is the current behavior.
    --hijack_netrw_behavior: "disabled" -- don't hijack anything
    hijack_netrw_behavior: "open_in_split" -- the behavior you are looking for, force it to "split" mode
                                           -- regardless of what your config says.
  }
})
```

**Comment by cseickel** [comment] 2022-02-12 04:28
This is done and merged to **v1.x**. Use this option to get the desired behavior:

```lua
require("neo-tree").setup({
  filesystem = {
    hijack_netrw_behavior: "open_in_split"
})
```

**Closed by cseickel** 2022-02-12 04:28 UTC
Labels: enhancement

**Comment by wookayin** [comment] 2022-02-17 06:10
Works great with the `hijack_netrw_behavior = "open_in_split"` option. I expected it `:NeoTreeOpen` would **still open in the left vsplit window regardless of** hijacking, which I think is the most reasonable behavior, but it works as it is said: open in the current buffer. How would I achieve this if I want this, i.e., when running `:NeoTreeShow` / `:NeoTreeOpen` while respecting ` window = { position = ..., width = ... }` config?

**Comment by wookayin** [comment] 2022-02-17 06:27
I checked out the latest release again and it works perfectly as I expected.

With `filesystem.hijack_netrw_behavior = "open_split"` option (NOTE the typo, in this thread it was  incorrectly said `"open_in_split"`) set, `:split .` `:vsplit .` `edit .`, etc., all work well opening into the correct window, and `:NeoTreeToggle`, `:NeoTreeOpen`, etc. opens in the left like the previous default behavior. 

Thank you very much for implementing this tricky feature!
