### ISSUE TITLE
Neovim crashed on delete a opened buffer/file

### ISSUE THREAD

**Issue by nyngwang** [nvim-neo-tree/neo-tree.nvim#143] opened 2022-02-13 02:59 UTC
As title. I think this is a very serious bug. To reproduce:

1. Open a new neovim session in terminal via `nvim .`.
2. Open neo-tree, then open any existing unimportant file under `.`.
3. Open neo-tree again, then use `d` to delete that file.
4. You will have chance that your neovim session gets terminated and the entire tmux-window got broken.

I have experienced this at least three times, something a deletion didn't cause any bug. But now it just appeared again.

DEMO:

https://user-images.githubusercontent.com/24765272/153736434-84ecdece-3f08-4283-8787-f2e16aa55a35.mov

**Comment by cseickel** [comment] 2022-02-13 03:56
Should be fixed now. The problem is that I was calling `bwipeout` on the buffer when you delete the file, which is normally a good thing. In this case, if that file is the only one in the session aside from a floating window, that is not allowed.  I avoid the error, which likely caused your crash, by wrapping it in a pcall which will do nothing if it is an error. The downside is that now you have a buffer open for a file that has been deleted, but at least there is no crash.

The truth is that you really should not delete the only open file from a floating window. NeoVim does not like that.

**Closed** 2022-02-13 15:33 UTC
Labels: bug
