### ISSUE TITLE
Unexpected exit when buffer is closed

### ISSUE THREAD

**Issue by magidc** [nvim-neo-tree/neo-tree.nvim#720] opened 2023-01-26 21:04 UTC
Hi, I am experiencing an annoying issue when I close a buffer. I am using a tab manager to be able to to keep several buffers opened (https://github.com/akinsho/bufferline.nvim) but when I close a buffer via :bdelete, NVIM unexpectely shows message "Press ENTER or type command to continue " and, no matter what you do, it exits. 
This situation only happens when Neotree is opened. Also, if the option " close_if_last_window " is set to false, there is no sudden exit but Neotree expands into the whole screen even though there are other buffers still loaded.
I have replaced the tag manager with other (barbar) and the situation persists. If Neotree is opened, configured to close on last window, and a buffer is closed, Neovim exists. Is Neotree being confused with buffer closing event and it is not aware that there are other buffers still there?

**Comment by cseickel** [comment] 2023-01-26 22:26
This is a duplicate of #241, please see that issue for a suggestion on how to create the "close if last buffer" behavior you are looking for.

**Closed by cseickel** 2023-01-26 22:26 UTC
