### ISSUE TITLE
Ability to rename files in normal mode.

### ISSUE THREAD

**Issue by DasOhmoff** [nvim-neo-tree/neo-tree.nvim#662] opened 2022-12-21 19:31 UTC
Hey 👋, thank you for this nice plugin!

When I open the tree and hit `m` to rename the file under the cursor, it opens a popup window in which I can change the name. I would like to be able to change the name in normal mode, to be able to use all the shortcuts of neovim in it.

For example when I want to rename the file, I most of the time want to leave the file extension the same, so I would have to go back before the `.` in the file name in order to change the name only, without affecting the extension.

This forces
* using the arrow keys (which most people using vim dislike doing)
* and disallows things like easily copying and pasting file parts

How can I make this happen?

Thank you for your help :)

**Comment by cseickel** [comment] 2022-12-21 23:23
This is really a duplicate of #602. Head there to add to the discussion.

**Closed by cseickel** 2022-12-21 23:23 UTC
Labels: duplicate

**Comment by DasOhmoff** [comment] 2022-12-22 08:35
Ah ok. Thanks
