### ISSUE TITLE
BufWinEnter and WinEnter are not triggered

### ISSUE THREAD

**Issue by fitrh** [nvim-neo-tree/neo-tree.nvim#571] opened 2022-10-17 12:12 UTC
Using the following init file

```lua
vim.opt.number = true
vim.opt.relativenumber = true

local plugins = {
    "plenary.nvim",
    "nui.nvim",
    "neo-tree.nvim",
}
for _, plugin in ipairs(plugins) do
    vim.api.nvim_command("packadd " .. plugin)
end

local neotree = {}
neotree.ok, neotree.module = pcall(require, "neo-tree")
if neotree.ok then
    neotree.module.setup()
end

local augroup = vim.api.nvim_create_augroup("Minimal", {})
vim.api.nvim_create_autocmd({ "BufWinEnter", "WinEnter" }, {
    group = augroup,
    callback = function()
        vim.api.nvim_win_set_option(0, "relativenumber", true)
    end,
})
vim.api.nvim_create_autocmd({ "WinLeave" }, {
    group = augroup,
    callback = function()
        vim.api.nvim_win_set_option(0, "relativenumber", false)
    end,
})
```

We should have the current window using relative line numbers and the other
using absolute line numbers, with the following steps

1. Open a file
2. Run `:Neotree toggle`
3. Press `q`

The expected behavior is after neotree closed, the current window have a relative
line numbers, but it seems that neither `BufWinEnter` nor `WinEnter` event are triggered

**Comment by cseickel** [comment] 2022-10-17 14:28
It works as expected for me. When you ran the minimal test, did you open neovim with this command? (assuming the above file is saved as `minimal_init.lua`)

```
nvim -u minimal_init.lua --noplugin
```

I am using this version of neovim:
```
NVIM v0.9.0-dev-18-ga93ff5fc6
```

**Comment by fitrh** [comment] 2022-10-17 15:05
Current behavior

https://user-images.githubusercontent.com/55179750/196212667-50937290-c92f-4f9c-ad5a-2fca9ac87564.mp4

Expected behavior, just like when navigating with window command

https://user-images.githubusercontent.com/55179750/196213246-7ed7f313-72c5-40ef-8935-3b3c601f584e.mp4

**Comment by cseickel** [comment] 2022-10-17 15:26
This minimal init doesn't actually work for me because I don't have these plugins installed into `opt`. Can you create a minimal init that sets a new pack path and installs the plugins so that it is truly minimal and isolated from any existing configuration? I would do it myself but I am short on time right now.

**Comment by fitrh** [comment] 2022-10-18 03:21
> This minimal init doesn't actually work for me because I don't have these plugins installed into `opt`

I moved those packages to `$XDG_DATA_HOME/nvim/site/pack/minimal/start`

```lua
-- neotree.lua
local set = vim.opt
set.cursorline = true
set.number = true
set.relativenumber = true
set.termguicolors = true
set.wrap = false

require("neo-tree").setup()

local augroup = vim.api.nvim_create_augroup("Minimal", {})
vim.api.nvim_create_autocmd({ "BufWinEnter", "WinEnter" }, {
    group = augroup,
    callback = function()
        vim.api.nvim_win_set_option(0, "relativenumber", true)
    end,
})
vim.api.nvim_create_autocmd({ "WinLeave" }, {
    group = augroup,
    callback = function()
        vim.api.nvim_win_set_option(0, "relativenumber", false)
    end,
})
```

```sh
nvim --clean -S neotree.lua -- neotree.lua
```

**Comment by cseickel** [comment] 2022-10-18 13:20
That doesn't work at all. I get this error:

```
Error detected while processing command line..script /home/cseickel/neotree.lua:
E5113: Error while calling lua chunk: /home/cseickel/neotree.lua:9: module 'neo-tree' not found:
        no field package.preload['neo-tree']
        no file './neo-tree.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/neo-tree.lua'
        no file '/usr/local/share/lua/5.1/neo-tree.lua'
        no file '/usr/local/share/lua/5.1/neo-tree/init.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/neo-tree.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/neo-tree/init.lua'
        no file './neo-tree.so'
        no file '/usr/local/lib/lua/5.1/neo-tree.so'
        no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/neo-tree.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /home/cseickel/neotree.lua:9: in main chunk
Press ENTER or type command to continue
```

```
❯ ls $XDG_DATA_HOME/nvim/site/pack/minimal/start
neo-tree.nvim  nui.nvim  plenary.nvim
```

I also tried moving that `minimal` folder to be a sibling of my actual packer folder location which is in `.local/share/nvim/site/pack`, but that did not make those plugins load. I think if neo-tree is loaded for you when you do this, maybe you are not actually running a clean config.

**Comment by fitrh** [comment] 2022-10-18 13:24
> maybe you are not actually running a clean config.

`:h --clean`

**Comment by cseickel** [comment] 2022-10-18 13:29
What is `$XDG_DATA_HOME` for you?

**Comment by fitrh** [comment] 2022-10-18 13:30
It is `~/.local/share`

**Comment by cseickel** [comment] 2022-10-18 13:45
So how does neo-tree and dependencies get loaded with `--clean` if you have installed them into a user config folder and are not explicitly loading them in your minimal session file? Do you have these plugins installed somewhere else where they are acting like builtins?

**Comment by fitrh** [comment] 2022-10-18 13:53
See `:h 'rtp'` and `:h packages-runtimepath`

**Comment by fitrh** [comment] 2022-10-18 13:55
Here is another minimal config, the `'rtp'` now only contains neo-tree and its dependencies

```lua
local set = vim.opt
set.cursorline = true
set.number = true
set.relativenumber = true
set.termguicolors = true
set.wrap = false
set.rtp = ""

for _, plugin in ipairs({ "plenary.nvim", "nui.nvim", "neo-tree.nvim" }) do
    set.rtp:append(
        os.getenv("XDG_DATA_HOME") .. "nvim/site/pack/minimal/start/" .. plugin
    )
end

require("neo-tree").setup()

local augroup = vim.api.nvim_create_augroup("Minimal", {})
vim.api.nvim_create_autocmd({ "BufWinEnter", "WinEnter" }, {
    group = augroup,
    callback = function()
        vim.api.nvim_win_set_option(0, "relativenumber", true)
    end,
})
vim.api.nvim_create_autocmd({ "WinLeave" }, {
    group = augroup,
    callback = function()
        vim.api.nvim_win_set_option(0, "relativenumber", false)
    end,
})
```

**Comment by cseickel** [comment] 2022-10-18 14:26
> As long as it's under `rtp`, you can directly access lua modules under `lua`, right?

Usually, but when you start with the `--clean` switch, those directories are ignored. It certainly won't work for me.

**Comment by cseickel** [comment] 2022-10-18 14:28
Also, if you load neo-tree in this way, you are skipping some of the plugin initialization and there will be no `:Neotree` commands available. If you have a working `:Neotree` command, plugins are being loaded from somewhere.

**Comment by fitrh** [comment] 2022-10-18 14:35
> there will be no :Neotree commands available

`require('neo-tree').setup()` provides us `Neotree` command, right?

> plugins are being loaded from somewhere

Sorry, I'm a bit confused, but how can it be if my rtp is only contains
3 directories?

**Comment by cseickel** [comment] 2022-10-18 14:42
> require('neo-tree').setup() provides us Neotree command, right?

No. The user commands come from https://github.com/nvim-neo-tree/neo-tree.nvim/blob/v2.x/plugin/neo-tree.vim which would be automatically run when the plugin is loaded through normal means. The setup call would not run that file.

> Sorry, I'm a bit confused, but how can it be if my rtp is only contains
> 3 directories?

I believe your plugins were already loaded before the session file was even read.


I would bet that if you open neovim with this command:

```
nvim --clean
```

You can still use the `:Neotree toggle` command. This is not intuitive, but it seems to me that it is the case on your computer.

**Comment by cseickel** [comment] 2022-10-18 15:14
When I move the plugins to the tmp directory and use your updated session file, I can use the Neotree command. Also, the relative numbers work as expected and there is no bug.

Since your earlier minimal inits should not have worked, and I can't recreate the bug at all, I have to conclude that the problem is some configuration that is unique to your machine. Most likely there are other plugins being loaded that you are not aware of which is causing conflicts.

**Comment by fitrh** [comment] 2022-10-18 15:48
> Most likely there are other plugins being loaded that you are not aware of which is causing conflicts.


I'm sure there aren't any other plugins since I've cleaned up my `site` and even
my config directory, so there's nothing but the default nvim installation files

And I can still reproduce this issue with the following steps

1. `nvim -u NONE -i NONE --noplugin`
2. `:so neotree.lua`
3. `:e neotree.lua`
4. `:Neotree toggle`
5. Press `q`

I'll probably try it tomorrow on another machine

**Comment by nyngwang** [comment] 2022-11-24 03:38
@fitrh Did you solve it?

If not: What's your result of calling `:au Minimal`? It's also possible that you might clean-up your `augroup Minimal` somewhere so these dedicated events never got registered.

**Comment by fitrh** [comment] 2022-11-24 03:49
@nyngwang No, I've been busy with work lately

The augroup are not cleaned, and I have not face this issue
with similar plugins like nvim-tree or litee

**Comment by pysan3** [comment] 2024-03-08 11:55
This should be fixed by 

- https://github.com/MunifTanjim/nui.nvim/pull/349

And since this is being discussed at https://github.com/nvim-neo-tree/neo-tree.nvim/issues/1211, I'll close this one to keep the discussion in one place.

If you still experience this issue **after the PR at nui has been merged**, please report it on the above issue and ping me.

**Closed by pysan3** 2024-03-08 11:55 UTC
