### ISSUE TITLE
BUG: Indentation for files seems to be broken.

### ISSUE THREAD

**Issue by oneslash** [nvim-neo-tree/neo-tree.nvim#924] opened 2023-05-11 13:23 UTC
I am working on a project where the file `main.tf` is located in the following path `AWS/eu-west-1/INFLUX/production/main.tf`.

The tree renders `main.tf` as it is on the same level as `production` folder

![Screenshot 2023-05-11 at 2 43 40 PM](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/15870134/5b55131c-fd01-460f-b9f8-a9011dbbe3a9)

**Comment by pysan3** [comment] 2023-05-24 10:50
I cannot reproduce it.

Does it happen with other file name as well?

Your screen shot does not show the left end of the buffer. How far is the indentation?

It would be very nice if you could provide more details.

**Comment by alptibet** [comment] 2023-06-04 10:09
+1

**Comment by oneslash** [comment] 2023-06-04 15:05
@alptibet good catch, yes indeed it works well if I create another file or folder.

**Comment by pysan3** [comment] 2023-06-04 15:51
> i think I have found a pattern here

@alptibet Thanks a lot for the detailed explanation and screenshots. But I still cannot reproduce this error...

Could you send your config options for neo-tree you are using now? (CC @oneslash)

I'm also wondering how you managed to bring `src` folder at the same indent as `~/DEV/test`. I thought that option was deleted quite some time ago.

**Comment by oneslash** [comment] 2023-06-04 16:57
@pysan3, hi thank you 🙏 

I use vanilla Astronvim config, https://github.com/AstroNvim/AstroNvim/blob/main/lua/plugins/neo-tree.lua

**Comment by pysan3** [comment] 2023-06-06 04:14
@oneslash 

Quick update. Thanks for the link and I was able to reproduce the error.

The cause was this line and I will look into how to fix it.

https://github.com/AstroNvim/AstroNvim/blob/a137a014ef579122482d05cc8a58fd5f0dcc916d/lua/plugins/neo-tree.lua#L22

**Comment by alptibet** [comment] 2023-06-06 14:09
@pysan3 , sorry for late response. I also use vanilla astronvim config.

**Comment by pysan3** [comment] 2023-06-06 16:32
Thanks for both of you guys. 

I was able to diagnose the error and will fix it when I've got time. Please wait till this weekend or so ;)

**Comment by oneslash** [comment] 2023-06-06 20:46
@pysan3, thank you very much!

**Comment by alptibet** [comment] 2023-06-07 15:43
@pysan3, thank you!

**Comment by pysan3** [comment] 2023-06-09 12:43
Closing with #977

**Closed by pysan3** 2023-06-09 12:43 UTC
