### ISSUE TITLE
group empty directories

### ISSUE THREAD

**Issue by cseickel** [nvim-neo-tree/neo-tree.nvim#216] opened 2022-03-27 13:45 UTC
> [ ] group empty directories (compact folders that only contain a single folder into one node in the file tree)

This feature does not exist.

_Originally posted by @cseickel in https://github.com/nvim-neo-tree/neo-tree.nvim/issues/211#issuecomment-1079934404_

**Comment by nyngwang** [comment] 2022-04-18 16:03
Lol, this sounds so Java.

**Comment by caenrique** [comment] 2022-04-22 10:50
this would be very nice

**Comment by cseickel** [comment] 2022-04-28 02:18
I just pushed this to `main`. It's on by default for the `"buffers"` source only. To enable it for the `"filesystem"` source, add this option:
```lua
    require("neo-tree").setup({
      filesystem = {
        group_empty_dirs = true,
      }
    })
```

**Comment by axieax** [comment] 2022-04-28 05:46
Thanks for implementing this feature! Not sure why but can we render collapsible directories earlier as well. Please see the demo where directory `lua` and only subdirectory `axie` are rendered as nested directories initially, but become `lua/axie` (expected behaviour) after toggling the neo-tree.

https://user-images.githubusercontent.com/62098008/165684916-08fe787e-c66e-4807-b10e-cb8dc406a0e4.mp4

**Comment by cseickel** [comment] 2022-04-28 11:19
The problem there is that those folders are being lazy loaded and the grouping only runs on a on the set of folders being loaded in a particular scan, which is just the one level for a lazy load.

I think what I should do is that when a folder is opened that contains nothing but a single sub folder, I should keep loading children until I get to the end of what should be collapsed so I can group the set of dirs in one go.

**Comment by cseickel** [comment] 2022-04-30 01:31
Ok, this is fixed. I did not end up trying to look ahead and pre-group folders, I feel like that would be a dangerous can of worms I don't want to get into. 

It was surprisingly difficult to get this right. What it does now is that as you drill down into a folder that should be grouped, it just adds that extra level onto the current folder.

**Comment by axieax** [comment] 2022-04-30 04:11
Thanks for the fix! I think a great part of this feature would be to reduce keystrokes when expanding directories, so having to press `<CR>` to expand multiple times is not ideal (nvim-tree doesn't have this issue). Totally understand if it'll be too buggy tho!

**Comment by nyngwang** [comment] 2022-04-30 06:44
@axieax But then it will be inconvenient to create a folder/file in the middle level.

**Comment by axieax** [comment] 2022-04-30 10:50
> But then it will be inconvenient to create a folder/file in the middle level.

Oh that's true, although it shouldn't be too many extra steps with #269. I feel like navigation of nested folders is a more common use case than adding a file/folder within a middle level, especially since once this file/folder is added, `group_empty` will no longer be needed, so adding future files/folders won't require this much expansion.

**Comment by cseickel** [comment] 2022-04-30 14:51
> Thanks for the fix! I think a great part of this feature would be to reduce keystrokes when expanding directories, so having to press `<CR>` to expand multiple times is not ideal (nvim-tree doesn't have this issue). Totally understand if it'll be too buggy tho!

I'm mostly concerned with performance issues. Right now I only fetch one level at a time and lazy load everything else. Pre-grouping requires pre-fetching recursively and then I have to deal with those users that have performance issues because they have 10,000 folders in their project, or who knows what other issue affecting their performance.

The deciding factor for me is that I don't actually like the feature for the "filesystem" source myself, so I don't want to do anything risky with it. Someone else could try to take it on and I'd entertain a PR. I mainly did it because I wanted the feature for the "buffers" source which doesn't need any lazy loading at all.

**Comment by cseickel** [comment] 2022-04-30 14:55
> @axieax But then it will be inconvenient to create a folder/file in the middle level.

That could be confusing at first, but you can always input the new file/folder name with `../file.txt` and it will work even after the grouping happens.

**Closed** 2022-04-30 23:54 UTC
Labels: enhancement
