### ISSUE TITLE
How to keep Neotree open when press `<Esc>` to cancel window-picker selection.

### ISSUE THREAD

**Issue by nyngwang** [nvim-neo-tree/neo-tree.nvim#306] opened 2022-04-18 14:25 UTC
As title. I'm from https://github.com/nvim-neo-tree/neo-tree.nvim/issues/221. The current behavior is that the neo-tree will get closed.

**Comment by cseickel** [comment] 2022-04-18 14:53
You can set `close_floats_on_escape_key = false` in your config and then use `q` to close instead.

**Comment by nyngwang** [comment] 2022-04-18 15:51
@cseickel: Is it possible to map the behavior to `<Esc>` instead of `q`?

**Comment by cseickel** [comment] 2022-04-18 16:16
The `q` mapping should work regardless of whether `close_floats_on_escape_key` is true or false. Is it possible you have mapped `q` to something else in your config?

**Comment by nyngwang** [comment] 2022-04-18 16:22
I just removed my mapping(I mapped it to `none`). But after that, I tried `q` and still got the same result: it closed the floating neo-tree.

**Comment by cseickel** [comment] 2022-04-18 16:30
I am very confused. The goal is to close Neo-tree with `q`, but not when you press `<Esc>`, isn't it? If so, this should do it:

```lua
  require('neo-tree').setup({
    close_floats_on_escape_key = true,
    -- You can control the `q` mapping at the global level
    window = {
      mappings = {
        ["q"] = "close_window",
      },
    },
   -- OR you can apply it for the "filesystem" source specifically
    filesystem = {
      window = {
        mappings = {
          ["q"] = "close_window",
        }
      },
    }
  })

```

Just don't map `q` to "none", because that will disable it entirely.

**Comment by nyngwang** [comment] 2022-04-18 16:38
@cseickel:

> [...] The goal is to close Neo-tree with q, but not when you press <Esc>, isn't it? [...]

Not exactly. During the selection of the window-picker(those purple statuslines got shown) and press whatever(both `q` and `<Esc>` are OK) to cancel the selection **and back to the neo-tree**. But the neo-tree got closed in the demo below.


https://user-images.githubusercontent.com/24765272/163840677-9fb97bbd-9446-46c6-a961-f36a56c946f5.mov

**Comment by cseickel** [comment] 2022-04-18 16:49
OK, but what I was trying to say is that if you use `<Esc>` to cancel the window selection, but `<Esc>` also closes the window, then the solution is to make it so that `<Esc>` does not close the neo-tree window. Does this work correctly when `close_floats_on_escape_key = false` is set?

**Comment by nyngwang** [comment] 2022-04-18 16:59
I always set `close_floats_on_escape_key = false` on every try. The following all have the same result:

1. `<Esc>` to `none`
2. `<Esc>` not set in the `mappings`
3. Either 1. or 2. combined with either `q` not set or `q` set to `none`.

**Comment by cseickel** [comment] 2022-04-19 00:50
I'm not sure where else to go with this. When I initiate the window picker and then hit Esc to cancel, it never closes the floating neo-tree window, no matter what my neo-tree settings are. 

Maybe I'm misunderstanding. Can you give me a play by play of every key press so I can be sure I am testing the right thing?

**Comment by nyngwang** [comment] 2022-04-19 01:07
@cseickel:

https://user-images.githubusercontent.com/24765272/163900172-861ae4bb-b4e6-4b47-b629-51c76cbc600c.mov

**Comment by cseickel** [comment] 2022-04-24 14:13
@nyngwang Sorry to just ignore this. The problem is that this doesn't happen for me at all. When I activate the window picker and then hit escape to cancel, it doesn't close my neo-tree window, even if Escape is currently configured to close it. This might be something that is unique to your config.

**Comment by nyngwang** [comment] 2022-04-26 01:21
@cseickel: Probably because I was using `position = 'float'`. Anyway I have changed to use `'left'`.

**Comment by cseickel** [comment] 2022-04-26 11:56
@nyngwang I'm sure it can't happen without using a float position, but I did actually try it with a floating window and still did not experience the issue. 

This means it was probably something unique to your setup. If you are no longer using it in a way that causes this problem, I'll just close it.

**Closed by cseickel** 2022-04-26 11:56 UTC
