### ISSUE TITLE
NeoTree throwing error when quickly opening it with the telescope search-window open

### ISSUE THREAD

**Issue by 0xaf2f6ad** [nvim-neo-tree/neo-tree.nvim#432] opened 2022-07-15 09:12 UTC
This happened quite frequently but I figured out now how to reproduce it. So sharing it

### Required environment

I think these 2 are the only ones, if it does not come up then I'll leave a whole list of possible culprits 

- Telescope 
- NeoTree (ofc)

## Steps to reproduce

- open up the telescope (you need to be in insert mode) (I had a keybind `<Leader>s`
- hit escape (go to normal mode) 
- then immediately open up neotree to search something (I had a keybind `\` to open it up)

And the stacktrace should come up

### The Stacktrace and post-error

`The stacktrace`
![neotreestacktrace](https://user-images.githubusercontent.com/69459394/179190800-54e92af8-7b88-43e7-b644-12b995a60c78.png)

This is what happens when I hit enter after the error is thrown

![neotree-bug](https://user-images.githubusercontent.com/69459394/179190342-113daa28-385c-4ca6-8bf5-f5db6dcc5b06.png)

The window is not save-able, so I can just close the buffer and it goes away but it came up quite frequently while I was quickly switching btw my project files so I thought it would be good to put it out there :^]

### What should have happened

Possibly, telescope window should have closed and the neotree window should just have opened up, or no window opens up at all as a fall-back

If this is happening due to telescope maybe then let me know!

**Comment by cseickel** [comment] 2022-07-23 01:14
I'm closing because I think the issue is that Telescope is probably making a mistake with autocmds where it thinks it's closing its own window but it's actually closing other plugins' windows.

If I had time I would identify the issue in Telescope and put in a PR, but there's too many other things I want to work on and this one doesn't affect my usage.

**Closed by cseickel** 2022-07-23 01:14 UTC
Labels: wontfix
