### ISSUE TITLE
open dir with only hidden files report error

### ISSUE THREAD

**Issue by qixiao986** [nvim-neo-tree/neo-tree.nvim#459] opened 2022-07-30 02:30 UTC
When in a dir with only hidden files, open neo-tree will show error:
`[Neo-tree ERROR] debounce  filesystem_navigate  error:  .../packer/start/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:241: attempt to index a nil value`

![output](https://user-images.githubusercontent.com/3962171/181866756-dab2d526-7322-4f62-97f6-8f723ea7692d.gif)

**Comment by cseickel** [comment] 2022-07-30 13:17
This is a duplicate of #458 which had been fixed in `main` but had not been released yet. I just made that release, if you update now it should be fixed.

**Closed by cseickel** 2022-07-30 13:17 UTC
