### ISSUE TITLE
The cursor on a NeoTree window resets after expanding a directory

### ISSUE THREAD

**Issue by wookayin** [nvim-neo-tree/neo-tree.nvim#111] opened 2022-02-02 18:08 UTC
When pressing `<CR>` to expand a directory or folder, the cursor should remain at the same location while expanding the subdirectory.

However, the currrent cursor moves to a weird random location such as some previously open files or even to the very first line of the window. It is not quite easy to reproduce but I do see this quite often.

### Demo

In the following video, I never jumped the cursor within the neotree window -- the only keys I've pressed are `j`, `k` (down/up) and `Enter` to open a directory/file. No `gg`, `G`, `C-o`, etc.

![Demo](https://user-images.githubusercontent.com/1009873/152211763-d983f679-613e-4b38-836f-de868cb8a199.gif)

For example:

- I open the file `events/init.lua`
- Next, navigate to `sources/` dir and expand it by pressing `<CR>`
- The subtree expands, and the cursor immediately reset to `init.lua` (the currently open file on the right)
- I then try to expand the directory `buffer/lib/`, and then the cursor goes to the first line of the explorer

**Comment by cseickel** [comment] 2022-02-02 19:40
Do you have `follow_current_file` turned on? If so, can you try turning it off and telling me if it changes the behavior? I noticed you have a scrollbar plugin, can you try disabling that and tell me if it has an effect?

If you have a dotfiles repo or can post your full config, it may offer clues.

**Comment by wookayin** [comment] 2022-02-03 00:42
I was using the default setup with no custom config (just `.setup { }` call with empty table), so I think `follow_current_file` is turned on by default. I can confirm that turning that off makes the behavior OK (i.e., no bug)

I also turned off the scrollbar plugin and it seems it works okay also. I'm not 100% confident because the bug is not always reproducible, but I feel like this didn't happen anymore.

**Comment by cseickel** [comment] 2022-02-03 00:55
It's likely the interaction between `follow_current_file` and the scrollbar. This is why I stopped using scrollbars, there were too many conflicts with other plugins.

I'd like to make it work though. Which scrollbar are you using?

**Comment by wookayin** [comment] 2022-02-03 01:05
I am using https://github.com/dstein64/nvim-scrollview.

**Comment by cseickel** [comment] 2022-02-05 01:44
@wookayin I just pushed some refactored code to **main** that I think will fix this problem. I was only able to make this bug happen for me once so it's hard for me to confirm, but it does fix other bugs that are related to race debouncing refreshes.

**Comment by nyngwang** [comment] 2022-02-05 01:54
@cseickel: Thanks for the fix. Since I encounter this more frequently(why?) if this still happens, I will report it here.

**Comment by wookayin** [comment] 2022-02-07 17:14
Thanks for implementing caa64cf0e4. I am in the v1.29 branch now, and today I've run into this again a few times. Looks like the bug has been fully resolved -- just letting you know. I will take some time if allowed to investigate this issue also.

**Comment by cseickel** [comment] 2022-02-07 17:24
I'm, a little confused, are you saying this bug IS or is NOT fixed?

**Comment by wookayin** [comment] 2022-02-07 17:26
@cseickel My bad, sorry, I meant "hasn't been fully resolved".

**Comment by cseickel** [comment] 2022-02-07 17:39
👍 Got it. I'll re-open the issue.

One thing that I suspected as being the is the vim autocmd events used to detect changes to files. One thing to try is to set `use_libuv_file_watcher = true` in your `filesystem` config.

**Comment by wookayin** [comment] 2022-02-07 20:01
Can you please re-open the issue?  FYI I have `follow_current_file = false` and `filesystem.use_libuv_file_watcher = true` and the cursor movement is still flaky.

**Comment by cseickel** [comment] 2022-02-07 20:18
I think this may be related to certain options or plugins you have that I don't. Can you provide a link to your config or a minimal config that reproduces the issue?

**Comment by nyngwang** [comment] 2022-02-08 23:51
@cseickel  I experience this too. Sometimes when I open the (floating) neo-tree, it doesn't focus the cursor on the current buffer/file. It was moved to the top. And I have a plugin that changes the `pwd` whenever I move my cursor between windows, but the neo-tree doesn't sync-up too, even after I run the `...Toggle` twice.

**Comment by nyngwang** [comment] 2022-02-08 23:58
I think this one should have a higher priority. Since it's impossible to re-enable it inside the same session, I will have to restart `nvim` (so all layout are lost) when it happen. This is **really** annoying...

**Comment by wookayin** [comment] 2022-02-17 06:27
In the current main (v1.37), this still hasn't been fixed.

**Comment by nyngwang** [comment] 2022-02-21 02:57
@wookayin: If the file you want to reveal is not under the current parent folder(i.e. the result of the last time you opened it), then your cursor will be put at the parent.

I haven't encountered this bug since [the last comment by @cseickel ](https://github.com/nvim-neo-tree/neo-tree.nvim/issues/111#issuecomment-1037616436) above.

**Comment by cseickel** [comment] 2022-02-26 23:17
Hey @wookayin, since this is not happening to me I'm not going to be able to fix it. Let me know if you can find a way to recreate the issue with a minimal config that I can test out. If I don't hear from you in the next few days I will close the issue.

**Comment by wookayin** [comment] 2022-02-28 01:06
@cseickel Well, the problem still presents. I will try reproducing minimal config, but seems not trivial. However, the bug is always reproducible for me. If you are not bothered, you are also welcomed to directly try out my dotfiles: https://github.com/wookayin/dotfiles. Please have this opened until we figure out something.

**Comment by wookayin** [comment] 2022-02-28 01:13
Actually I was able to reproduce the issue with the following minimal config:
```
packadd neo-tree.nvim
packadd nui.nvim
packadd plenary.nvim

let mapleader=','           " comma is the <Leader> key.
nmap <leader>E  :NeoTreeRevealToggle<CR>
```

Just out-of-box, no `.setup{}` call. What I did:

- Open NeoTree.
- Expand `somedir/`
- Open `somedir/somefile`
- Expand `another_directory/`
- At this point, cursor moves to `somedir/somefile`

My environment is macOS (M1) 12.0, NVIM v0.7.0-dev+1032-g01e58fb14. 

Would you be able to reproduce the bug?

**Comment by cseickel** [comment] 2022-02-28 23:52
I am seeing some random jumping around with a minimal init and no setup() call. I'll dig in and find the issue.

**Comment by cseickel** [comment] 2022-03-01 01:43
Now that I know what the issue was, I can't believe it hasn't affected me before now.

@wookayin  I think I got it, can you try out **main** and let me know if it seems fixed?

**Comment by wookayin** [comment] 2022-03-01 02:19
@cseickel Thanks! Glad you figured out and it was such an easy fix once you knew why. I can confirm the bug is fixed in the main branch.

**Closed** 2022-03-01 13:16 UTC
Labels: bug
