### ISSUE TITLE
UX enhancement: bootstrap speed kinda slow

### ISSUE THREAD

**Issue by nyngwang** [nvim-neo-tree/neo-tree.nvim#100] opened 2022-01-28 00:27 UTC
As title. I'm not sure whether this is possible to do but I think the current startup speed after triggering `NeoTreeFloatToggle` is kinda slow. It takes about 0.7s to show all the directories in the filetree.

**Comment by cseickel** [comment] 2022-01-28 02:50
There's a lot of possibilities here. Can you tell me:

1. What branch are you on? When was it last updated?
2. Is it any different if you switch to **main**?
3. How many folders/files in the directory you are showing, does it matter if it is a small one?
4. Is it a git repo? If so, is it faster when you disable gits status with `enable_git_status=false`?
5. Do you have `filesystem.filters.respect_git_ignore = false`?
6. If not, can you set that and tell me if it makes it faster?
7. Can you try disabling other plugins that might react to new windows? A minimal config with just neo-tree would be the best test.

**Comment by cseickel** [comment] 2022-02-05 02:45
@nyngwang I'm going to close this as it seems plenty fast enough to me. It's also possible that some of the recent bug fixes have sped it up.

**Comment by nyngwang** [comment] 2022-02-05 12:53
@cseickel: thanks, this is not a serious problem actually.

**Comment by datwaft** [comment] 2022-02-11 05:37
I am having a similar problem, but instead of being like 0.7 seconds it looks to be multiple seconds:

[![asciicast](https://asciinema.org/a/468260.svg)](https://asciinema.org/a/468260)

Here is the url if you cannot see the asciinema: https://asciinema.org/a/468260

**Comment by nyngwang** [comment] 2022-02-11 06:54
To providing motivation for this optimization: I remember I can __hold__ the toggle key of nvim-tree.lua and the tree can on average complete a open-close round in 0.1s, so it blinked soothly.

**Comment by cseickel** [comment] 2022-02-11 12:39
@datwaft It's really helpful to know that it happens in your docker container! I see your dotfiles, I'll try it out later and troubleshoot.

**Comment by datwaft** [comment] 2022-02-11 13:52
> @datwaft It's really helpful to know that it happens in your docker container! I see your dotfiles, I'll try it out later and troubleshoot.

To clarify, I couldn't reproduce it in the docker container. It was instantly fast even with tmux and zsh installed.

I haven't tried with my full dotfiles in the container yet, but commenting my whole zshrc doesn't seem to so anything.

**Comment by cseickel** [comment] 2022-02-12 01:04
@datwaft We do have logging that can be enabled that may provide clues. To use it, set these variables in your config:

```lua
      require("neo-tree").setup({
        log_level = "trace",
        log_to_file = true,
      })
```

Then restart nvim, open the window once, and then run:
```
:NeoTreeLogs
```

Which will open the log file in a new tab. Can you copy and paste or attach that log file?

You will want to change those settings back after you are done, the `trace` level outputs a lot and there is no file rotation in place.

**Comment by wookayin** [comment] 2022-02-12 02:01
You may find this way of doing profiling useful:
```
:profile start /tmp/nvim-profile.log | profile func * | profile file *
:(do some slow command)
:profile pause
```
and then the log file will show you which function (not lua functions though) is slow.

**Comment by datwaft** [comment] 2022-02-12 04:37
> @datwaft We do have logging that can be enabled that may provide clues. To use it, set these variables in your config:
> 
> ```lua
>       require("neo-tree").setup({
>         log_level = "trace",
>         log_to_file = true,
>       })
> ```
> 
> Then restart nvim, open the window once, and then run:
> 
> ```
> :NeoTreeLogs
> ```
> 
> Which will open the log file in a new tab. Can you copy and paste or attach that log file?
> 
> You will want to change those settings back after you are done, the `trace` level outputs a lot and there is no file rotation in place.

Here is the log: http://0x0.st/oXDA.txt

I just opened neo-tree using NeoTreeReveal and closed the neo-tree window after that.

**Comment by datwaft** [comment] 2022-02-12 04:43
> You may find this way of doing profiling useful:
> 
> ```
> :profile start /tmp/nvim-profile.log | profile func * | profile file *
> :(do some slow command)
> :profile pause
> ```
> 
> and then the log file will show you which function (not lua functions though) is slow.

Here is the log for this: http://0x0.st/oXDm.txt

I just opened neo-tree using NeoTreeReveal this time.

**Comment by cseickel** [comment] 2022-02-12 13:53
> Here is the log: http://0x0.st/oXDA.txt
> 
> I just opened neo-tree using NeoTreeReveal and closed the neo-tree window after that.

That was helpful in that it eliminated a lot of possibilities. Neo-tree is doing what it should, it just takes a long time to either:

- Read the files and directories
- Subscribe to change events on the directories
- Run `git status --porcelain=v1`

Can you test with the following changes:

- Start from a different directory. The ultimate test would be to create a new directory just for this and add a few dummy .txt files.
- Disable the file watcher by setting `filesystem.use_libuv_file_watcher = false` in your setup
- Disable the git status feature by setting `enable_git_status = false` in your setup (you can also run the command yourself in the test directory and see if it runs instantly or not)

**Comment by nyngwang** [comment] 2022-02-12 23:24
> To provide motivation for this optimization: I remember I can **hold** the toggle key of nvim-tree.lua and the tree can on average complete a open-close round in 0.1s, so it blinked smoothly. Everything can be largely speeded up, should be speeded up.

@cseickel: this problem has been resolved. I'm satisfied with the current speed.

**Comment by cseickel** [comment] 2022-02-26 23:25
@datwaft I'm going to close this issue. I think the remaining slowdown you are experiencing is something unique to your computer. I don't see much more that I can do on my end.

For the extra slowness in a git repo, there have been improvemnts made there, see https://github.com/nvim-neo-tree/neo-tree.nvim/discussions/152

**Closed by cseickel** 2022-02-26 23:25 UTC
Labels: bug, enhancement

**Comment by datwaft** [comment] 2022-02-26 23:27
Thanks for your help! I will try to find the cause.

Btw, I tested it in a Windows computer inside the WSL with my dotfiles and everything and there is a delay there too.

**Comment by cseickel** [comment] 2022-02-26 23:36
> Thanks for your help! I will try to find the cause.

Let me know If you have any questions at all while you are troubleshooting.
