### ISSUE TITLE
Diagnostics not shown when opened for the first time until buffer is edited/opening a new buffer

### ISSUE THREAD

**Issue by lyonelz96** [nvim-neo-tree/neo-tree.nvim#901] opened 2023-04-26 22:07 UTC
Yo!

I noticed this and I'm not sure if it's a setting I missed or something to do with the LSP rather than the plugin.
I'm using [lazy.nvim](https://github.com/folke/lazy.nvim) and this is my spec:

```lua
return {
    "nvim-neo-tree/neo-tree.nvim",
    lazy = false,
    branch = "v2.x",
    dependencies = {
        "nvim-lua/plenary.nvim",
        "nvim-tree/nvim-web-devicons",
        "MunifTanjim/nui.nvim",
    },
    opts = {
        filesystem = {
            hijack_netrw_behavior = "open_current",
        },
    },
    keys = {
        {
            "<leader>fe",
            function()
                require("neo-tree.command").execute({
                    toggle = true,
                    reveal = true,
                })
            end,
            desc = "[F]ile [E]xplorer",
        },
    },
}
```
I'll use an example using [flake8](https://flake8.pycqa.org/en/latest/) (A linter for python)

Here's a ```minimal.lua``` config to reproduce:

```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	"folke/tokyonight.nvim",
	-- add any other plugins here
	"williamboman/mason.nvim",
	"jay-babu/mason-null-ls.nvim",
	"jose-elias-alvarez/null-ls.nvim",
	{
		"nvim-neo-tree/neo-tree.nvim",
		branch = "v2.x",
		dependencies = {
			"nvim-lua/plenary.nvim",
			"nvim-tree/nvim-web-devicons", -- not strictly required, but recommended
			"MunifTanjim/nui.nvim",
		},
	},
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here

require("mason").setup()
require("mason-null-ls").setup({
    ensure_installed = { "flake8" },
    handlers = {},
})
require("null-ls").setup()
```
1. Create a folder I'll name it DEBUG ```mkdir DEBUG && cd DEBUG```
2. Create two python files ```touch hello.py bye.py```
3. Open neovim with the config to install everything ```nvim -u minimal.lua```
4. Wait for everything to install and open of the python files ```:e hello.py```
5. You should see an error ```blank line at the end of file```
6. Open neo-tree ```:Neotree``` and the error is not showing up

To make it show up you can do one of the following:
1. Using neotree open the other python file ```bye.py``` and the errors should update
2. Edit the current buffer (Enter insert mode, write something , then go back to normal mode)

I'm assuming it has something to do with when the UI reloads on neo-tree.

https://user-images.githubusercontent.com/43832900/234713553-b03e161b-fd37-4416-b87d-83eb4ee0a943.mov

**Comment by ur4ltz** [comment] 2023-04-27 16:45
Install this plugin

https://github.com/mrbjarksen/neo-tree-diagnostics.nvim

**Comment by pysan3** [comment] 2023-05-24 11:25
The information about diagnostics stored in neo-tree is only updated on the autocmd event `DiagnosticChanged`.

By definition this is only triggered when some diagnostic changes in any buffer, so would never be triggered by opening neo-tree.

So this is kinda _it's a feature, not a bug_ thing now.

What do you think @cseickel ?

It will be a pretty easy fix, since what we need to do is to simply run this once somewhere at the first execution.

```lua
    state.diagnostics_lookup = utils.get_diagnostic_counts()
```

**Comment by cseickel** [comment] 2023-05-24 12:48
Agreed @pysan3. It would probably make sense to run that right at the location where the DiagnosticChanged event is subscribed to.

**Comment by pysan3** [comment] 2023-05-24 13:12
> It would probably make sense to run that right at the location where the DiagnosticChanged event is subscribed to.

Unfortunately not quite. It is subscribed inside `setup` for each source (example [here](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/e5594d53986b34e584e8afe2ea6ad99d6f6d2105/lua/neo-tree/sources/filesystem/init.lua#L360)), but this is called way before creating a `state`.

The `state` is created for each source for each tab. Besides, if we blindly apply the same method as the subscribed event, we will be calling `redraw` everytime. [here](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/e5594d53986b34e584e8afe2ea6ad99d6f6d2105/lua/neo-tree/sources/manager.lua#L258).

So we need to run it on creation of `state` instead.

I'll work on it this weekend if possible. :)

**Comment by pysan3** [comment] 2023-06-09 13:41
Closing with #978

**Closed by pysan3** 2023-06-09 13:41 UTC
