### ISSUE TITLE
BUG: Unable to expand directory with large number of files

### ISSUE THREAD

**Issue by rv-ragul** [nvim-neo-tree/neo-tree.nvim#1022] opened 2023-07-02 08:02 UTC
### Did you check docs and existing issues?

- [X] I have read all the docs.
- [X] I have searched the existing issues.
- [X] I have searched the existing discussions.

### Neovim Version (nvim -v)

NVIM v0.10.0-dev-628f6cc

### Operating System / Version

Linux debian 6.3.0-1-amd64

### Describe the Bug

"**Failed to spawn process**" when expanding nodes in a directory which contains large number of files.
But it works perfectly in directories with less number of files. 
_Note_: I have not done any special tweaks in the neo-tree configs. I am using default configurations.
I have attached the screenshots of error messages in the following section.

In the following **_Your configurations section_**, I have assigned the key "Z" to "expand_all_nodes".

### Screenshots, Traceback

![error](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/85612319/ca08d5ce-9fbe-4a25-a997-878e1cd70a13)
![error(remaining)](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/85612319/67206095-4f5a-4a53-88c0-1db889bb333a)
![stack traceback](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/85612319/963184ef-0976-4ada-a5ac-262b5f05e9c1)
![stack traceback2](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/85612319/7539081d-310d-46bf-a21e-4ab96c2009f7)

### Steps to Reproduce

1. Open a $HOME directory(or any other directory with large number of files)
2. Expand the nodes
3. Now the error should come.

### Expected Behavior

Error should not occur when expanding nodes in the directory with large number of files.

### Your Configuration

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  -- add any other plugins here
}

local neotree_config = {
  "nvim-neo-tree/neo-tree.nvim",
  dependencies = { "MunifTanjim/nui.nvim", "nvim-tree/nvim-web-devicons", "nvim-lua/plenary.nvim" },
  cmd = { "Neotree" },
  keys = {
    { "<Leader>e", "<Cmd>Neotree<CR>" }, -- change or remove this line if relevant.
  },
  opts = {
    -- Your config here
    -- ...
        window = {
            mappings = {
                ["Z"] = "expand_all_nodes",
            }
        }

  },
}

table.insert(plugins, neotree_config)
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by miversen33** [comment] 2023-07-02 13:48
Likely duplicate of #997

**Closed by miversen33** 2023-07-02 13:48 UTC
Labels: bug
