### ISSUE TITLE
Restoring a session containing a neo-tree sidebar breaks neo-tree

### ISSUE THREAD

**Issue by dhazel** [nvim-neo-tree/neo-tree.nvim#740] opened 2023-02-09 18:13 UTC
Thanks for the great plugin!

Neovim version: 0.8.2
OS: Windows 10

Steps to reproduce:

1. Open neovim
2. Open the neo-tree sidebar, `:Neotree`
3. Save the session, `:mksession mysession.vim`
4. Close neovim
5. Open neovim
6. Restore the session, `:source mysession.vim`
7. Observe that the sidebar is created but neo-tree does not render in the sidebar
8. Attempt to toggle the neotree sidebar, `:Neotree`
9. Observe that neo-tree does not render and an error is thrown in messages:

````
Error executing vim.schedule lua callback: ...vim-data/lazy/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:867: Failed to rename buffer
stack traceback:
	[C]: in function 'nvim_buf_set_name'
	...vim-data/lazy/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:867: in function 'create_window'
	...vim-data/lazy/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:1015: in function 'draw'
	...vim-data/lazy/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:1177: in function 'show_nodes'
	...ree.nvim/lua/neo-tree/sources/filesystem/lib/fs_scan.lua:98: in function 'render_context'
	...ree.nvim/lua/neo-tree/sources/filesystem/lib/fs_scan.lua:126: in function <...ree.nvim/lua/neo-tree/sources/filesystem/lib/fs_scan.lua:125>
````

**Comment by nhat-vo** [comment] 2023-02-10 11:12
Hi! Indeed, this looks like a bug. The neo-tree buffer was saved along with the session, and neo-tree is unable to overwrite that buffer when it is created again. A workaround would be to close the tree before creating the session. I will have a look to see if there is any way to do this automatically.

**Comment by nyngwang** [comment] 2023-02-18 20:20
@nhat-vo Does #748 resolve this now?

**Comment by nhat-vo** [comment] 2023-02-19 12:46
Yes, thanks for reminding me. I thought the issue will automatically be closed on PR merge.

**Comment by cseickel** [comment] 2023-02-19 15:11
> Yes, thanks for reminding me. I thought the issue will automatically be closed on PR merge.

The issue will get automatically closed on **release** in this repo. It's not a big deal either way if you want to close it on merge to `main` though.

**Comment by ehaynes99** [comment] 2023-02-20 03:12
I don't think this actually works. The function executes, but restoring a session like `nvim -S Session.vim`, I end up with the restored session having these buffers:
```
:buffers
  9 #    "~/all-workspaces/external/neo-tree.nvim/README.md" line 1
 10 %a   "lua/neo-tree/ui/renderer.lua" line 32
 11  a   "neo-tree filesystem [1]"      line 0
```
the `neo-tree filesystem` buffer is normal size and blank. Toggling the tree resumes the proper behavior.

Also, plugins like `auto-session` open session files like this:
```
silent source <SESSION_FILE>
```
In this case, the `clean_neotree_buffers` function is never called.

**Comment by nhat-vo** [comment] 2023-02-21 11:35
Good point! I actually thought of adding the cleanup step right after a session was load, but somehow forgot about it.

**Comment by nyngwang** [comment] 2023-02-22 16:40
Can confirm that your fix works. A minor issue is that there is a blink after restoring the session (so I did see the empty split was there and got closed during restoring)

**Comment by treatybreaker** [comment] 2023-02-23 02:10
Unfortunately, at least for me, this fix causes the file tree to randomly close on opening some files in git projects.

It's related to `clean_invalid_neotree_buffers`. I don't have an autosession plugin or anything like that, so I'm not quite sure what's loading a session that would kick off the closing of the neotree sidebar.

**Comment by nhat-vo** [comment] 2023-02-23 08:10
@treatybreaker thanks for letting me know. Could you tell me how to reproduce it? I tried to open files from the git source, but it was running fine.

**Comment by treatybreaker** [comment] 2023-02-24 01:38
Apologies for not responding until now. I'm going to dig into tonight and see if I can't get a reproducible error action.

Lets close this issue out and if I'm still seeing the issue with a bare bones nvim install, I'll open an issue reporting it. Could just be something funk with my config.

**Comment by treatybreaker** [comment] 2023-02-24 19:20
@nhat-vo 

#771 resolves the issues I had above. It was occurring for me with just a simple config with only neo-tree in it. I no longer have the issue when pointing lazy to your ref in #771.

**Comment by cseickel** [comment] 2023-03-01 12:42
Hi everyone, I just pushed a bit of a breaking change to the new session cleanup functionality. The feature which automatically cleans broken neo-tree buffers restored from a session is now opt-in. If you want to keep it, you need to add this option to your config:

```lua
  auto_clean_after_session_restore = false, -- Automatically clean up broken neo-tree buffers saved in sessions
```

**Closed** 2023-03-28 07:07 UTC
Labels: bug
