### ISSUE TITLE
Synchronize comments in defaults.lua

### ISSUE THREAD

**Issue by ur4ltz** [nvim-neo-tree/neo-tree.nvim#905] opened 2023-04-28 13:20 UTC
Comments in defaults.lua got messed up on lines 0,,30. 
Key code popup_border_style.

**Comment by miversen33** [comment] 2023-04-28 14:23
I'm not seeing anything jumping out at me as incorrect in that section. Could you copy and paste into a comment here the relevant bits of the doc you believe are incorrect?

Additionally, feel free to submit a PR for that. The documentation needs alot of love lol

**Comment by ur4ltz** [comment] 2023-04-28 14:33
Search popup_border_style

**Comment by miversen33** [comment] 2023-04-28 14:52
Ahh I see it. Maybe next time actually post the issue though instead of saying "just go look again". Its significantly more helpful to see exactly what you believe is incorrect as opposed to trying to figure out what you mean.

To those who might stumble on this, the issue is [here](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/c5367ffbfccec9ee5d22ee097e3f2eb6a5ab3625/lua/neo-tree/defaults.lua#L15-L17)

```lua
  close_if_last_window = false, -- Close Neo-tree if it is the last window left in the tab
  -- popup_border_style is for input and confirmation dialogs.
  -- Configurtaion of floating window is done in the individual source sections.
  -- "NC" is a special style that works well with NormalNC set
  close_floats_on_escape_key = true,
  ```
  
  These comments should be (merged?) with [line 40](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/c5367ffbfccec9ee5d22ee097e3f2eb6a5ab3625/lua/neo-tree/defaults.lua#L40)
  ```lua
  popup_border_style = "NC", -- "double", "none", "rounded", "shadow", "single" or "solid"
  ```
  
  Feel free to submit a PR to correct the documentation :)

**Comment by miversen33** [comment] 2023-04-28 15:42
Understood. I have tagged this and it will maybe eventually get addressed lol. Thank you for raising the issue :)

**Closed** 2024-01-03 19:03 UTC
Labels: documentation, good-first-issue
