### ISSUE TITLE
Spurious error message when deleting file

### ISSUE THREAD

**Issue by heyvito** [nvim-neo-tree/neo-tree.nvim#991] opened 2023-06-15 04:21 UTC
Hi there!

I just noticed something odd every time I delete a file using the <kbd>d</kbd> key. Although the file is deleted and correctly removed from the tree, an error message is displayed on my window: `Could not remove file: (...)`. I tried to get logs, but I don't think there's anything too relevant there, anyway I'm attaching it here just in case:

<details>
<summary>neo-tree.nvim.log</summary>

```
[TRACE Thu Jun 15 00:48:54 2023] ....nvim/lua/neo-tree/sources/filesystem/lib/fs_actions.lua:396: Deleting node:  /Users/victorgama/.config/nvim/lua/vito/core/colorscheme.lua
[TRACE Thu Jun 15 00:48:54 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:97: Firing event:  vim_win_enter  with args:  {
  afile = "neo-tree filesystem [2]"
}
[TRACE Thu Jun 15 00:48:54 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:81: Handler  neo-tree-win-enter  for vim_win_enter called successfully.
[TRACE Thu Jun 15 00:48:54 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:97: Firing event:  vim_buffer_enter  with args:  {
  afile = ""
}
[TRACE Thu Jun 15 00:48:54 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:97: Firing event:  neo_tree_popup_buffer_enter  with args:  nil
[TRACE Thu Jun 15 00:48:54 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:81: Handler  {
  event = "vim_buffer_enter",
  handler = <function 1>
}  for vim_buffer_enter called successfully.
[TRACE Thu Jun 15 00:48:54 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:81: Handler  buffers.vim_buffer_enter  for vim_buffer_enter called successfully.
[TRACE Thu Jun 15 00:48:54 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:81: Handler  filesystem.vim_buffer_enter  for vim_buffer_enter called successfully.
[TRACE Thu Jun 15 00:48:54 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:97: Firing event:  vim_buffer_modified_set  with args:  {
  afile = ""
}
[TRACE Thu Jun 15 00:48:54 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:67: Seed for vim_buffer_modified_set returned: table: 0x01040dffd0
[TRACE Thu Jun 15 00:48:54 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:81: Handler  buffers.vim_buffer_modified_set  for vim_buffer_modified_set called successfully.
[TRACE Thu Jun 15 00:48:54 2023] ...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:661: Redrawing tree filesystem 2
[TRACE Thu Jun 15 00:48:54 2023] .../neo-tree.nvim/lua/neo-tree/sources/common/container.lua:300: wanted width:  14  actual width:  37
[TRACE Thu Jun 15 00:48:54 2023] .../neo-tree.nvim/lua/neo-tree/sources/common/container.lua:300: wanted width:  3  actual width:  35
[TRACE Thu Jun 15 00:48:54 2023] .../neo-tree.nvim/lua/neo-tree/sources/common/container.lua:300: wanted width:  4  actual width:  33
[TRACE Thu Jun 15 00:48:54 2023] .../neo-tree.nvim/lua/neo-tree/sources/common/container.lua:300: wanted width:  4  actual width:  31
[TRACE Thu Jun 15 00:48:54 2023] .../neo-tree.nvim/lua/neo-tree/sources/common/container.lua:300: wanted width:  9  actual width:  29
[TRACE Thu Jun 15 00:48:54 2023] .../neo-tree.nvim/lua/neo-tree/sources/common/container.lua:300: wanted width:  15  actual width:  29
[TRACE Thu Jun 15 00:48:54 2023] .../neo-tree.nvim/lua/neo-tree/sources/common/container.lua:300: wanted width:  15  actual width:  29
[TRACE Thu Jun 15 00:48:54 2023] .../neo-tree.nvim/lua/neo-tree/sources/common/container.lua:300: wanted width:  11  actual width:  29
[TRACE Thu Jun 15 00:48:54 2023] .../neo-tree.nvim/lua/neo-tree/sources/common/container.lua:300: wanted width:  9  actual width:  31
[TRACE Thu Jun 15 00:48:54 2023] .../neo-tree.nvim/lua/neo-tree/sources/common/container.lua:300: wanted width:  10  actual width:  31
[TRACE Thu Jun 15 00:48:54 2023] .../neo-tree.nvim/lua/neo-tree/sources/common/container.lua:300: wanted width:  12  actual width:  35
[TRACE Thu Jun 15 00:48:54 2023] .../neo-tree.nvim/lua/neo-tree/sources/common/container.lua:300: wanted width:  16  actual width:  35
[TRACE Thu Jun 15 00:48:54 2023] ...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:663:   Redrawing tree done filesystem 2
[TRACE Thu Jun 15 00:48:54 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:81: Handler  filesystem.vim_buffer_modified_set  for vim_buffer_modified_set called successfully.
[TRACE Thu Jun 15 00:48:54 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:81: Handler  git_status.vim_buffer_modified_set  for vim_buffer_modified_set called successfully.
[TRACE Thu Jun 15 00:48:57 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:97: Firing event:  vim_win_closed  with args:  {
  afile = "1004"
}
[DEBUG Thu Jun 15 00:48:57 2023] ...hare/nvim/lazy/neo-tree.nvim/lua/neo-tree/setup/init.lua:728: VIM_WIN_CLOSED: disposing state for window 1004
[TRACE Thu Jun 15 00:48:57 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:81: Handler  {
  event = "vim_win_closed",
  handler = <function 1>
}  for vim_win_closed called successfully.
[TRACE Thu Jun 15 00:48:57 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:97: Firing event:  vim_win_closed  with args:  {
  afile = "1005"
}
[DEBUG Thu Jun 15 00:48:57 2023] ...hare/nvim/lazy/neo-tree.nvim/lua/neo-tree/setup/init.lua:728: VIM_WIN_CLOSED: disposing state for window 1005
[TRACE Thu Jun 15 00:48:57 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:81: Handler  {
  event = "vim_win_closed",
  handler = <function 1>
}  for vim_win_closed called successfully.
[TRACE Thu Jun 15 00:48:57 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:97: Firing event:  vim_win_enter  with args:  {
  afile = "neo-tree filesystem [2]"
}
[TRACE Thu Jun 15 00:48:57 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:81: Handler  neo-tree-win-enter  for vim_win_enter called successfully.
[TRACE Thu Jun 15 00:48:57 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:97: Firing event:  vim_buffer_enter  with args:  {
  afile = "neo-tree filesystem [2]"
}
[TRACE Thu Jun 15 00:48:57 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:97: Firing event:  neo_tree_buffer_enter  with args:  nil
[TRACE Thu Jun 15 00:48:57 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:81: Handler  {
  event = "vim_buffer_enter",
  handler = <function 1>
}  for vim_buffer_enter called successfully.
[TRACE Thu Jun 15 00:48:57 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:81: Handler  buffers.vim_buffer_enter  for vim_buffer_enter called successfully.
 [TRACE Thu Jun 15 00:48:57 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:81: Handler  filesystem.vim_buffer_enter  for vim_buffer_enter called successfully.
[TRACE Thu Jun 15 00:48:57 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:97: Firing event:  file_deleted  with args:  /Users/victorgama/.config/nvim/lua/vito/core/colorscheme.lua
```

</details>

Please do let me know in case you need any further information!

**Comment by heyvito** [comment] 2023-06-16 00:24
Small update: I noticed creating files (using the <kbd>a</kbd> key) also shows an interesting warning: `[Neo-tree WARN] File already exists`. Is it possible to Neo-tree to be running the command twice? What can I do to diagnose this?

Just in case: I'm loading `nvim-neo-tree` through `lazy.nvim`. This is my current config:

```lua
-- plugins/neo-tree.lua

return {
  "nvim-neo-tree/neo-tree.nvim",
  cmd = "Neotree",
  branch = "v2.x",
  keys = {
    { "<leader>e", "<cmd>Neotree toggle<cr>", desc = "Toggle Neotree" },
  },
  dependencies = {
    "nvim-lua/plenary.nvim",
    "nvim-tree/nvim-web-devicons",
    "MunifTanjim/nui.nvim",
  },
  config = {
    filesystem = {
      follow_current_file = true,
    }
  }
}
```

(It may be important to say I'm quite new to Neovim; I'm coming from Vim)

**Comment by ibrahimWassouf** [comment] 2023-06-16 23:43
I came across this because I am also getting a message every time I move or delete a file

**Comment by MariaSolOs** [comment] 2023-06-18 01:50
I'm also experiencing the same issue. Happens sometimes when creating/removing a file with the `a` or `d` commands.

**Comment by pysan3** [comment] 2023-06-19 19:47
I'm pretty sure I had this same problem a few days ago but after I blindly rebuilt neovim and updated all plugins, I cannot reproduce this issue any more (I think you don't need to rebuild neovim tho).

I have no clue what is / was causing this issue but could you check again if you still have this issue now?

**Comment by MariaSolOs** [comment] 2023-06-20 04:01
> I'm pretty sure I had this same problem a few days ago but after I blindly rebuilt neovim and updated all plugins, I cannot reproduce this issue any more (I think you don't need to rebuild neovim tho).
> 
> I have no clue what is / was causing this issue but could you check again if you still have this issue now?

I recently updated my plugins and so far the issue hasn't happened again. That being said idk if it's fully fixed since it was quite flaky to begin with...

**Comment by heyvito** [comment] 2023-06-20 15:52
I also updated plugins a few days ago and the issue just went away. Couldn't reproduce it either. 👍🏻

I think it may be worth to keep this open so @MariaSolOs and @ibrahimWassouf can confirm if everything is stable at their end. Otherwise feel free to close it @pysan3. Thanks for the heads up! <3

**Comment by pysan3** [comment] 2023-06-21 02:41
@MariaSolOs @heyvito @ibrahimWassouf 

Thanks for your feedbacks! 

I think it’s safe to say that the issue is gone now. I believe it was a bug in plenary or something. 

Tho if you experience the same error again, feel free to mention me. Closing for now ;)

**Closed by pysan3** 2023-06-21 02:41 UTC
Labels: bug
