### ISSUE TITLE
BUG: Renaming when using alternative keyboard layout transliterates the name of the file into the layout

### ISSUE THREAD

**Issue by gerazov** [nvim-neo-tree/neo-tree.nvim#1370] opened 2024-03-01 10:43 UTC
### Did you check docs and existing issues?

- [X] I have read all the docs.
- [X] I have searched the existing issues.
- [X] I have searched the existing discussions.

### Neovim Version (nvim -v)

v0.9.4

### Operating System / Version

Manjaro

### Describe the Bug

When opening a file and having my `vim.opt.iminsert = 1` to write text in Cyrilics and I move to the `neo-tree` window and want to rename the file, the file name gets transliterated to Cyrilics.

### Screenshots, Traceback

![image](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/15214418/2a903696-dc88-4ceb-a038-130026fe9497)

### Steps to Reproduce

1. Change to alternate keyboard layout keymap
2. go to neo-tree
3. rename a file

### Expected Behavior

No transliteration should occur.

### Your Configuration

```Lua
--
```

**Comment by pysan3** [comment] 2024-03-02 09:18
@gerazov Unfortunately I'm not able to reproduce your problem (since I don't know Cyrilics...).

Could you copy your setup into the following code and see if the problem is reproducable?

Save this code into any file (like `repro.lua`) and then `:source repro.lua` inside neovim. You should see an input popup near your cursor.

If this code doesn't reproduce the issue, could you still send me list of options you set that might be affecting the issue?

```lua
local Input = require("nui.input")

--   ─────────────────────────────── Change lmap ───────────────────────────────
-- Please set your iminsert, langmap, keymap etc settings that might be relevant.
vim.cmd([[
" set iminsert=0
" set iminsert=1
" set langmap=zy,yz,ZY,YZ
]])
-- or using lua
-- vim.opt...

-- please paste some default input value that will be affected.
local default_value = "zyZY"
--   ─────────────────────────────── Change lmap ───────────────────────────────

local popup_options = {
  relative = "cursor",
  position = {
    row = 1,
    col = 0,
  },
  size = 20,
  border = {
    style = "rounded",
    text = {
      top = "[Input]",
      top_align = "left",
    },
  },
  win_options = {
    winhighlight = "Normal:Normal",
  },
}

local input = Input(popup_options, {
  prompt = "> ",
  default_value = default_value,
  on_close = function()
    print("Input closed!")
  end,
  on_submit = function(value)
    print("Value submitted: ", value)
  end,
  on_change = function(value)
    print("Value changed: ", value)
  end,
})

input:mount()
```

**Comment by MunifTanjim** [comment] 2024-03-03 07:42
Hello... This could be something that `nui.nvim` never handled, because nobody reported it... or could be an upstream `neovim` issue. We need to be able to reproduce it for being sure where the issue is.

**Comment by MunifTanjim** [comment] 2024-03-03 07:54
When you set `vim.opt.iminsert = 1`, it sets that option globally. So when you open a new float/split, that float/split will also have `iminsert=1`. This is how neovim behaves.

If you only want to set `iminsert = 1` for a specific buffer, do `vim.opt_local.iminsert = 1` or `:setlocal iminsert=1`.

**Comment by MunifTanjim** [comment] 2024-03-03 07:59
I'm not sure if `nui.nvim` can have a patch for this. It might make sense for a file tree plugin to always have `iminsert=0` for its popup... but different behavior can be desired in a different use-case.

If `neo-tree` decides it should always be `iminsert=0`, it can use the `buf_options` to do that: https://github.com/MunifTanjim/nui.nvim/blob/main/lua/nui/popup/README.md#buf_options

**Comment by pysan3** [comment] 2024-03-03 08:56
@MunifTanjim I think this is caused because you pass `"t"` as the second argument to `nvim_feedkeys` here.

https://github.com/MunifTanjim/nui.nvim/blob/b81333d12f824dbed5eb231c8a4409a290fdd848/lua/nui/input/init.lua#L97

I'm not actually sure what quirks will happen but I think you can temporary set `iminsert` to 0 before feeding the keys and then setting it back to the old value right after that.

**Comment by MunifTanjim** [comment] 2024-03-03 09:25
Oh, I didn't realize it's happening for `default_value`. I thought we're talking about when user is typing.

If the suggested fix solves the issue, it should definitely be merged into `nui.nvim`.

**Comment by pysan3** [comment] 2024-03-03 09:32
Oh, I thought OP was talking about the default value being translated to cyrilics letters. And I couldn't reproduce it as well: https://github.com/nvim-neo-tree/neo-tree.nvim/issues/1370#issuecomment-1974743023.

Did you type the _new name_ yourself @gerazov , and requesting neo-tree to default to english keyboard in input fields?

**Comment by MunifTanjim** [comment] 2024-03-03 09:49
Nevermind, I reproduced it.

- Do `:set keymap=greek_utf-8`
- Open neo-tree
- Open rename popup

@pysan3 can you verify that https://github.com/MunifTanjim/nui.nvim/pull/347 solves it?

**Comment by pysan3** [comment] 2024-03-03 09:54
I'm currently not on my PC so please wait a day or so 

I remember "t" was chosen to solve this issue. https://github.com/MunifTanjim/nui.nvim/issues/257

Does your change not bring this issue again?

**Comment by MunifTanjim** [comment] 2024-03-03 09:57
Ah man 🤣 damn! I completely forgot about that. Thanks so much for bringing that up. I'll do some more testing before merging this.

It should also have unit tests... last time I tried to add unit test for this, I failed. I'll try to do that again.

**Comment by MunifTanjim** [comment] 2024-03-03 10:10
So, https://github.com/MunifTanjim/nui.nvim/issues/257 was caused because of `"n", false`.

And this issue is caused because of `"t"`.

Looks like

```lua
vim.api.nvim_feedkeys(self._.default_value, "n", true)
```

solves both issues.

**Comment by pysan3** [comment] 2024-03-03 10:29
Glad to hear that.

TBH I don't know how `nvim_feedkeys` works and cannot understand the difference between those options :kekw:.

I've tested your PR branch and can confirm that your fix does solve the issue.

Thanks a lot on working on it!

**Comment by pysan3** [comment] 2024-03-04 05:10
Problem will be dealt upstream.

Closing on our end.
Please ping me again if this fix does not solve the problem @gerazov .
I hope I can hear from you again as it was difficult to iron out the problem without your interaction.

- https://github.com/MunifTanjim/nui.nvim/pull/347

**Closed by pysan3** 2024-03-04 05:10 UTC
Labels: bug, question

**Comment by gerazov** [comment] 2024-03-04 13:57
Hey guys - sorry for the silence - I haven't had the time to read through your discussion till today.

Yes the issue was that the filenames was transliterated to the keymap setting and you've fixed it - I've updated to https://github.com/MunifTanjim/nui.nvim/commit/fbb139c6f14896b434d0229099e1acd863ae6bec and it works!

:pray: thanks a million!
