### ISSUE TITLE
BUG: open + close + open fails

### ISSUE THREAD

**Issue by hackaugusto** [nvim-neo-tree/neo-tree.nvim#1417] opened 2024-03-27 12:17 UTC
### Did you check docs and existing issues?

- [X] I have read all the docs.
- [X] I have searched the existing issues.
- [X] I have searched the existing discussions.

### Neovim Version (nvim -v)

NVIM v0.9.5

### Operating System / Version

MacOS 14.4.1

### Describe the Bug

`Neotree` fails with:

```
[Neo-tree ERROR] debounce  filesystem_navigate  error:  .../packer/start/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:1036: Vim:E95: Buffer with this name already exists
```

### Screenshots, Traceback

<img width="847" alt="Screenshot 2024-03-27 at 13 14 26" src="https://github.com/nvim-neo-tree/neo-tree.nvim/assets/310139/8818bb00-8407-41e2-a651-711d8effe343">

### Steps to Reproduce

Run the following commands:

- `:Neotree`
- `:q`
- `:Neotree`

### Expected Behavior

Reopen neotree

### Your Configuration

```Lua
https://github.com/hackaugusto/dotfiles/blob/d00d42654a07715dde52013a029bfb60cd12c245/.config/nvim/init.lua
```

**Comment by pysan3** [comment] 2024-03-27 17:21
A. Are you on the latest commit / release?

B. Could you try this option and set it to true?

https://github.com/nvim-neo-tree/neo-tree.nvim/blob/16d1b194376bf1fc2acd89ccb3c29ba8315bfcea/lua/neo-tree/defaults.lua#L13

**Comment by pysan3** [comment] 2024-03-27 17:48
Duplicate of 
- https://github.com/nvim-neo-tree/neo-tree.nvim/issues/1415

**Closed by pysan3** 2024-03-27 17:48 UTC
Labels: bug, question
