### ISSUE TITLE
With `bind_to_cwd = true`, one still needs to press `R` to refresh neo-tree to reveal the cwd.

### ISSUE THREAD

**Issue by nyngwang** [nvim-neo-tree/neo-tree.nvim#619] opened 2022-11-24 02:11 UTC
As title.

### neo-tree
at b68ebd1

### nvim
```
NVIM v0.9.0-dev-377+gc9adbcafa
Build type: Release
LuaJIT 2.1.0-beta3
```

### related part of my config

```lua
filesystem = {
  hijack_netrw_behavior = 'open_default',
  follow_current_file = true,
  use_libuv_file_watcher = true,
  async_directory_scan = 'always',
  bind_to_cwd = true, -- sync neo-tree and vim's cwd.
  filtered_items = {
```

## attempts

maybe this is related to #609

**Comment by nyngwang** [comment] 2022-11-24 04:25
maybe this is related to #609

**Comment by cseickel** [comment] 2022-11-26 15:17
I had this happen once, but it did not repeat when I tried to test different commits. Can you make this happen reliably?

**Comment by cseickel** [comment] 2022-11-27 16:08
@nyngwang It's possible this was caused by using `auto_expand_width`. I just merged a fix to `main` to handle some issues there. Can you tell me if you still have this problem after updating?

**Closed** 2022-11-29 14:15 UTC
Labels: bug
