### ISSUE TITLE
failed to close an existed file without saving

### ISSUE THREAD

**Issue by zesty39** [nvim-neo-tree/neo-tree.nvim#870] opened 2023-04-13 09:52 UTC
hello , i get same error like #605,  when closing an existed file without saving

![neo-tree](https://user-images.githubusercontent.com/115854501/231722862-81069d97-f547-4d7c-a0d2-ffc818ff68e9.gif)

**Comment by cseickel** [comment] 2023-04-17 01:07
That's not a bug it's the feature that was added to fix #605. If you want to get an error from neovim itself rather than from neo-tree in this situation, set `close_if_last_window = false`.

**Comment by zesty39** [comment] 2023-04-17 01:22
I'm sorry to have failed to make myself clear. 

I know closing a new unsaved file is a warning. it show like this

`[Neo-tree WARN] Cannot close because an unnamed buffer is modified. Please save or discard this file.`

but cloing an existed file without saving. it same as #605.

`[Neo-tree ERROR] Error in event handler for event vim_win_enter[neo-tree-win-enter]: vim/_editor.lua:0: WinEnter Autocommands for "*"..script nvim_exec2() called at WinEnter Autocommands for "*":0: Vim(quit):E37: No write since last change`

I know the former is a feature, but I don't think the latter is either

**Comment by cseickel** [comment] 2023-04-17 01:55
Oh sorry, I get it now. Thanks for clarifying.

**Comment by smartinellimarco** [comment] 2023-05-15 18:22
I have the same issue, both for new and existing files. After the error message neo-tree relocates to the right.

**Comment by ghostbuster91** [comment] 2023-05-27 18:01
**Additional info**

Here is a trace for that error:
```

[TRACE Sat 27 May 2023 06:38:34 PM CEST] .//lua/neo-tree/events/queue.lua:97: Firing event:  vim_buffer_enter  with args:  {
  afile = ""
}
[TRACE Sat 27 May 2023 06:38:34 PM CEST] .//lua/neo-tree/events/queue.lua:81: Handler  {
  event = "vim_buffer_enter",
  handler = <function 1>
}  for vim_buffer_enter called successfully.
[TRACE Sat 27 May 2023 06:38:34 PM CEST] .//lua/neo-tree/events/queue.lua:81: Handler  buffers.vim_buffer_enter  for vim_buffer_enter called successfully.
[TRACE Sat 27 May 2023 06:38:34 PM CEST] .//lua/neo-tree/events/queue.lua:97: Firing event:  vim_win_closed  with args:  {
  afile = "1006"
}
[DEBUG Sat 27 May 2023 06:38:34 PM CEST] .//lua/neo-tree/setup/init.lua:724: VIM_WIN_CLOSED: disposing state for window 1006
[TRACE Sat 27 May 2023 06:38:34 PM CEST] .//lua/neo-tree/events/queue.lua:81: Handler  {
  event = "vim_win_closed",
  handler = <function 1>
}  for vim_win_closed called successfully.
[TRACE Sat 27 May 2023 06:38:34 PM CEST] .//lua/neo-tree/events/queue.lua:97: Firing event:  vim_win_closed  with args:  {
  afile = "1007"
}
[DEBUG Sat 27 May 2023 06:38:34 PM CEST] .//lua/neo-tree/setup/init.lua:724: VIM_WIN_CLOSED: disposing state for window 1007
[TRACE Sat 27 May 2023 06:38:34 PM CEST] .//lua/neo-tree/events/queue.lua:81: Handler  {
  event = "vim_win_closed",
  handler = <function 1>
}  for vim_win_closed called successfully.
[TRACE Sat 27 May 2023 06:38:37 PM CEST] .//lua/neo-tree/events/queue.lua:97: Firing event:  vim_win_closed  with args:  {
  afile = "1008"
}
[DEBUG Sat 27 May 2023 06:38:37 PM CEST] .//lua/neo-tree/setup/init.lua:724: VIM_WIN_CLOSED: disposing state for window 1008
[TRACE Sat 27 May 2023 06:38:37 PM CEST] .//lua/neo-tree/events/queue.lua:81: Handler  {
  event = "vim_win_closed",
  handler = <function 1>
}  for vim_win_closed called successfully.
[TRACE Sat 27 May 2023 06:38:37 PM CEST] .//lua/neo-tree/events/queue.lua:97: Firing event:  vim_win_closed  with args:  {
  afile = "1009"
}
[DEBUG Sat 27 May 2023 06:38:37 PM CEST] .//lua/neo-tree/setup/init.lua:724: VIM_WIN_CLOSED: disposing state for window 1009
[TRACE Sat 27 May 2023 06:38:37 PM CEST] .//lua/neo-tree/events/queue.lua:81: Handler  {
  event = "vim_win_closed",
  handler = <function 1>
}  for vim_win_closed called successfully.
[TRACE Sat 27 May 2023 06:38:38 PM CEST] .//lua/neo-tree/events/queue.lua:97: Firing event:  vim_win_closed  with args:  {
  afile = "1000"
}
[DEBUG Sat 27 May 2023 06:38:38 PM CEST] .//lua/neo-tree/setup/init.lua:724: VIM_WIN_CLOSED: disposing state for window 1000
[TRACE Sat 27 May 2023 06:38:38 PM CEST] .//lua/neo-tree/events/queue.lua:81: Handler  {
  event = "vim_win_closed",
  handler = <function 1>
}  for vim_win_closed called successfully.
[TRACE Sat 27 May 2023 06:38:38 PM CEST] .//lua/neo-tree/events/queue.lua:97: Firing event:  vim_win_enter  with args:  {
  afile = "neo-tree filesystem [1]"
}
[TRACE Sat 27 May 2023 06:38:38 PM CEST] .//lua/neo-tree/setup/init.lua:278: checking if last window
[TRACE Sat 27 May 2023 06:38:38 PM CEST] .//lua/neo-tree/setup/init.lua:279: prior window exists =  true
[TRACE Sat 27 May 2023 06:38:38 PM CEST] .//lua/neo-tree/setup/init.lua:280: win_count:  1
[TRACE Sat 27 May 2023 06:38:38 PM CEST] .//lua/neo-tree/setup/init.lua:286: last window, closing
[DEBUG Sat 27 May 2023 06:38:38 PM CEST] .//lua/neo-tree/setup/init.lua:292: close_if_last_window, modified files found:  {
  ["/home/kghost/workspace/neo-tree.nvim/lua/neo-tree/ui/renderer.lua"] = {
    loaded = true,
    modified = true
  }
}
[TRACE Sat 27 May 2023 06:38:38 PM CEST] .//lua/neo-tree/events/queue.lua:97: Firing event:  vim_buffer_enter  with args:  {
  afile = "lua/neo-tree/ui/renderer.lua"
}
[DEBUG Sat 27 May 2023 06:38:38 PM CEST] .//lua/neo-tree/setup/init.lua:242: redirecting buffer /home/kghost/workspace/neo-tree.nvim/lua/neo-tree/ui/renderer.lua to new split
[TRACE Sat 27 May 2023 06:38:38 PM CEST] .//lua/neo-tree/events/queue.lua:81: Handler  {
  event = "vim_buffer_enter",
  handler = <function 1>
}  for vim_buffer_enter called successfully.
[TRACE Sat 27 May 2023 06:38:38 PM CEST] .//lua/neo-tree/events/queue.lua:81: Handler  buffers.vim_buffer_enter  for vim_buffer_enter called successfully.
[TRACE Sat 27 May 2023 06:38:38 PM CEST] .//lua/neo-tree/events/queue.lua:97: Firing event:  vim_buffer_enter  with args:  {
  afile = "neo-tree filesystem [1]"
}
[TRACE Sat 27 May 2023 06:38:38 PM CEST] .//lua/neo-tree/events/queue.lua:97: Firing event:  neo_tree_buffer_enter  with args:  nil
[TRACE Sat 27 May 2023 06:38:38 PM CEST] .//lua/neo-tree/events/queue.lua:81: Handler  {
  event = "vim_buffer_enter",
  handler = <function 1>
}  for vim_buffer_enter called successfully.
[TRACE Sat 27 May 2023 06:38:38 PM CEST] .//lua/neo-tree/events/queue.lua:81: Handler  buffers.vim_buffer_enter  for vim_buffer_enter called successfully.
[ERROR Sat 27 May 2023 06:38:38 PM CEST] .//lua/neo-tree/events/queue.lua:83: Error in event handler for event vim_win_enter[neo-tree-win-enter]: vim/_editor.lua:0: WinEnter Autocommands for "*"..script nvim_exec2() called at WinEnter Autocommands for "*":0: Vim(quit):E37: No write since last change
[TRACE Sat 27 May 2023 06:38:38 PM CEST] .//lua/neo-tree/events/queue.lua:97: Firing event:  vim_buffer_enter  with args:  {
  afile = "neo-tree filesystem [1]"
}
[TRACE Sat 27 May 2023 06:38:38 PM CEST] .//lua/neo-tree/events/queue.lua:97: Firing event:  neo_tree_buffer_leave  with args:  nil
[TRACE Sat 27 May 2023 06:38:38 PM CEST] .//lua/neo-tree/events/queue.lua:97: Firing event:  neo_tree_buffer_enter  with args:  nil
[TRACE Sat 27 May 2023 06:38:38 PM CEST] .//lua/neo-tree/events/queue.lua:81: Handler  {
  event = "vim_buffer_enter",
  handler = <function 1>
}  for vim_buffer_enter called successfully.
```

**Comment by pysan3** [comment] 2023-06-21 20:15
Closing with #954.

**Closed** 2023-06-21 20:16 UTC
