### ISSUE TITLE
Howto keep current tree when switch to last buffer?

### ISSUE THREAD

**Issue by tmpm697** [nvim-neo-tree/neo-tree.nvim#999] opened 2023-06-19 10:13 UTC
I have this map:
```
map("n", "<leader>;", [[:e#<cr>]])
```
so when i press `leader` and `;`, neovim will switch to last buffer, this works but neo-tree will also close all other expanded folders, but this happens only on the first time i press `leader` and `;`, the second it's not happened, idk why.

steps:
```
tree folders:
fder1
  file1
  file2
fder2
  file3
  file4
1. select file1 and then select file3
2. select file4
3. press leader and ; to switch last buffer
4. observe now fder1 is collapsed and only fder2 is expaneded and buffer switched to file3
5. now select fder1 and select file1
6. select file2
7. switch buffer
8. observe that the tree structure is kept (fder1 and fder2 both expaneded), buffer switched to file1
```

so is there a way to always keep current tree structure in neo-tree despite of switch whatever buffer? especially using above mapping to switch last buffer?

i doubt that the switch buffer function from neovim causes this.

**Comment by pysan3** [comment] 2023-06-21 17:25
May I have the list of your current neo-tree configuration.

I bet this is caused by some specific combination of options such as `follow_current_file`, and it'll be easier to diagnose.

**Comment by tmpm697** [comment] 2023-06-21 17:46
> May I have the list of your current neo-tree configuration.
> 
> I bet this is caused by some specific combination of options such as `follow_current_file`, and it'll be easier to diagnose.

sure thing, this is my neotree config:
```
return {
	"nvim-neo-tree/neo-tree.nvim",
	dependencies = {
		"nvim-lua/plenary.nvim",
		"MunifTanjim/nui.nvim",
	},
	cmd = "Neotree",
	config = function()
		vim.cmd([[ let g:neo_tree_remove_legacy_commands = 1 ]])
		require("neo-tree").setup({
			renderers = {
				message = {
					{ "indent", with_markers = true },
					{ "name", highlight = "NeoTreeMessage" },
				},
			},
			use_default_mappings = false, -- no default mappings enable, define keybidings yourself
			close_if_last_window = false, -- Close Neo-tree if it is the last window left in the tab
			popup_border_style = "rounded",
			enable_git_status = true,
			enable_diagnostics = true,
			sort_case_insensitive = false, -- used when sorting files and directories in the tree
			sort_function = nil, -- use a custom function for sorting files and directories in the tree
			default_component_configs = {
				container = {
					enable_character_fade = true,
				},
				indent = {
					indent_size = 2,
					padding = 1, -- extra padding on left hand side
					with_markers = true,
					indent_marker = "│",
					last_indent_marker = "└",
					highlight = "NeoTreeIndentMarker",
					with_expanders = nil, -- if nil and file nesting is enabled, will enable expanders
					expander_collapsed = "",
					expander_expanded = "",
					expander_highlight = "NeoTreeExpander",
				},
				icon = {
					folder_closed = "",
					folder_open = "",
					folder_empty = "ﰊ",
					default = "*",
					highlight = "NeoTreeFileIcon",
				},
				modified = {
					symbol = "[+]",
					highlight = "NeoTreeModified",
				},
				name = {
					trailing_slash = false,
					use_git_status_colors = true,
					highlight = "NeoTreeFileName",
				},
				git_status = {
					symbols = {
						added = "", -- or "✚", but this is redundant info if you use git_status_colors on the name
						modified = "", -- or "", but this is redundant info if you use git_status_colors on the name
						deleted = "⊖", -- this can only be used in the git_status source
						renamed = "➜", -- this can only be used in the git_status source
						untracked = "★",
						ignored = "◌",
						unstaged = "✗",
						staged = "✓",
						conflict = "",
					},
				},
			},
			window = {
				position = "left",
				auto_expand_width = true,
				mapping_options = {
					noremap = true,
					nowait = true,
				},
				mappings = {
					["<space>"] = {
						"toggle_node",
						nowait = false, -- disable `nowait` if you have existing combos starting with this char that you want to use
					},
					["<tab>"] = "open",
					["l"] = "open",
					["h"] = "open",
					["<cr>"] = "open",
					["P"] = { "toggle_preview", config = { use_float = true } },
					["s"] = "open_vsplit",
					["z"] = "close_all_nodes",
					["Z"] = "expand_all_nodes",
					["a"] = {
						"add",
						config = {
							show_path = "none", -- "none", "relative", "absolute"
						},
					},
					["A"] = "add_directory", -- also accepts the optional config.show_path option like "add". this also supports BASH style brace expansion.
					["d"] = "delete",
					["r"] = "rename",
					["y"] = "copy_to_clipboard",
					["x"] = "cut_to_clipboard",
					["p"] = "paste_from_clipboard",
					["c"] = "copy", -- takes text input for destination, also accepts the optional config.show_path option like "add":
					["m"] = "move", -- takes text input for destination, also accepts the optional config.show_path option like "add".
					["q"] = "close_window",
					["R"] = "refresh",
					["?"] = "show_help",
					["<"] = "prev_source",
					[">"] = "next_source",
				},
			},
			nesting_rules = {},
			filesystem = {
				filtered_items = {
					visible = false, -- when true, they will just be displayed differently than normal items
					hide_dotfiles = true,
					hide_gitignored = true,
					hide_hidden = true, -- only works on Windows for hidden files/directories
					hide_by_name = {},
					hide_by_pattern = { -- uses glob style patterns
					},
					always_show = { -- remains visible even if other settings would normally hide it
					},
					never_show = { -- remains hidden even if visible is toggled to true, this overrides always_show
					},
					never_show_by_pattern = { -- uses glob style patterns
					},
				},
				follow_current_file = false, -- NOTE: -- This will find and focus the file in the active buffer every
				group_empty_dirs = false, -- when true, empty folders will be grouped together
				hijack_netrw_behavior = "open_current", --NOTE: -- netrw disabled, opening a directory opens neo-tree
				use_libuv_file_watcher = false, -- This will use the OS level file watchers to detect changes
				window = {
					mappings = {
						["-"] = "navigate_up",
						["."] = "set_root",
						["H"] = "toggle_hidden",
						["/"] = "filter_on_submit",
						["D"] = "fuzzy_finder_directory",
						["f"] = "fuzzy_finder",
						["<c-x>"] = "clear_filter",
						["[g"] = "prev_git_modified",
						["]g"] = "next_git_modified",
					},
				},
			},
			buffers = {
				follow_current_file = false, -- This will find and focus the file in the active buffer every
				group_empty_dirs = false, -- when true, empty folders will be grouped together
				show_unloaded = false,
				window = {
					mappings = {
						["bd"] = "buffer_delete",
						["<bs>"] = "navigate_up",
						["."] = "set_root",
					},
				},
			},
			git_status = {
				window = {
					position = "float",
					mappings = {
						["A"] = "git_add_all",
						["gu"] = "git_unstage_file",
						["ga"] = "git_add_file",
						["gr"] = "git_revert_file",
						["gc"] = "git_commit",
						["gp"] = "git_push",
						["gg"] = "git_commit_and_push",
					},
				},
			},
		})
	end,
}
```
If i have `follow_current_file` set to `false` as above config, switch buffers keep the tree structure but the pointer position in the tree does not change.

what i want is the pointer position change to buffer when switching but the tree structure keep stay.

**Comment by pysan3** [comment] 2023-06-21 17:49
> If i have follow_current_file set to false as above config, switch buffers keep the tree structure but the pointer position in the tree does not change.

> what i want is the pointer position change to buffer when switching but the tree structure keep stay.

Thanks for the config and clarification.
I understand your issue and was able to reproduce.

I'm currently investigating but not quite able to find a fix.
plz wait this this weekend ;)

**Comment by pysan3** [comment] 2023-06-21 18:54
@tmpm697 So, I was able to find the reason. It was actually done by purpose.

The discussion can be found in the following issue so please read it through.

- https://github.com/nvim-neo-tree/neo-tree.nvim/issues/45
  - https://github.com/nvim-neo-tree/neo-tree.nvim/issues/45#issuecomment-1009930238
  - https://github.com/nvim-neo-tree/neo-tree.nvim/issues/45#issuecomment-1009960976

So, funny fact that after over an year, we've got a vote for option A.

I don't know if you @cseickel remember this discussion, but shall we expose an user config option to switch the behaviors?
It will be a relatively easy fix as I think we only need to add some code here (and some documentation).

https://github.com/nvim-neo-tree/neo-tree.nvim/blob/8324fd52f7880bf17142f56b45f544d64eff5ac9/lua/neo-tree/sources/filesystem/init.lua#L99
![image](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/41065736/6ba27fdb-c2a3-413b-ac60-36bddef353b2)

**Comment by tmpm697** [comment] 2023-06-21 19:15
@pysan3 an option to auto or not auto collapse when change buffer and auto expand to current buffer keep the same?

currently it seems follow and expand.

please add if it's easy to fix, i have to re-track/re-open tree folders a lot by this.

**Comment by miversen33** [comment] 2023-06-21 19:44
> @pysan3 an option to auto or not auto collapse when change buffer and auto expand to current buffer keep the same?
> 
> please add if it's easy to fix, i have to re-track/re-open tree folders a lot by this.

Just to set expectations, things can take some time to get merged into the "main" branch (`v2.x` right now). Please have patience with FOSS projects :)

**Comment by cseickel** [comment] 2023-06-22 00:47
I actually don't love the idea of adding an option for this. I feel like we already have too many options and need to resist adding more, and this one seems like a real edge case to me. I remember when I originally wrote this that not having auto opened folders close themselves was messy and confusing.

Since we made it over a year without anyone asking for this option, I'd say it's not worth adding.

**Comment by pysan3** [comment] 2023-06-22 01:06
Hey @cseickel , you've got more votes for B here as well. 

https://github.com/nvim-neo-tree/neo-tree.nvim/issues/903

It's got upvotes as well so I don't think it's a minor opinion.

**Comment by cseickel** [comment] 2023-06-22 01:20
If you really want to add it @pysan3, I'll accept it. You put in enough work on this project to earn the right to add in a few pet features.

I'd like for the name to be clearly associated with the `follow_current_file` option, maybe something like `follow_current_file_without_closing_dirs` or maybe `follow_current_file` can optionally be a table like:

```lua
  follow_current_file = {
    enabled = true,
    leave_dirs_open = false
  },
```

One way to enable the feature would be to just add all folders to the `explicitly_opened_directories` collection when the follow logic is executed.

**Comment by pysan3** [comment] 2023-06-22 01:31
Thanks for your kindness. I'll work on it this weekend. 👍 

Besides, I might start listing some parts of the code that we can clean up or delete due to duplication. 
I believe the confusion of the options and code complexity is not coming from the amount but the structure of code and that the error traceback is hard to follow.

**Closed** 2023-07-05 16:05 UTC
Labels: documentation, enhancement, working-on-it
