### ISSUE TITLE
Greyed out folders with special characters

### ISSUE THREAD

**Issue by brunoperdigao** [nvim-neo-tree/neo-tree.nvim#508] opened 2022-09-07 15:40 UTC
Hi,

First, thanks for the awesome work.

I noticed that Neo-tree greys out folders named with special characters. I usually avoid using this kind of characters, but since I speak Portuguese, I end up using it once in a while. Is there a way I can disable this?

Example:
![image](https://user-images.githubusercontent.com/57102715/188920631-f6aac9d4-0a1e-4bd8-81c6-460dce92d4b9.png)

Edit: I forgot to mention that I am using Windows 10

**Comment by cseickel** [comment] 2022-09-07 16:09
It's certainly not intentional. I wonder if ti is being marked as hidden for some reason. Is it affect by toggling hidden items with `H`?

Could you copy and paste the folder name here so I can copy it to my computer and test it out?

**Comment by brunoperdigao** [comment] 2022-09-07 17:42
The name of the folder is `special-character-ç`. But I also tested with other characters like `à`, `á`, `â` or `ã`.
It is being marked as hidden when I press `H`
![image](https://user-images.githubusercontent.com/57102715/188943500-4c4cb179-9437-42aa-9ad2-492d59df4312.png)

**Comment by pysan3** [comment] 2023-06-25 15:09
Should be a duplicate of https://github.com/nvim-neo-tree/neo-tree.nvim/issues/731. 

Tho it's not solved yet, there are more discussions going over there so closing this issue to keep things in one place. 

Please mention me if your issue is different.

**Closed** 2023-06-25 15:09 UTC
