### ISSUE TITLE
Feature Req.: Is it possible to show indent-line for the filetree?

### ISSUE THREAD

**Issue by nyngwang** [nvim-neo-tree/neo-tree.nvim#93] opened 2022-01-23 15:58 UTC
As title. Just like the one nvim-tree.lua did.

<img src="https://user-images.githubusercontent.com/24765272/150686972-d6f55929-bf68-4fe5-a16f-401c382481e6.png" width="200">

Not related to the title: I also expect a way to customize the folder icon, please 🥺

**Comment by cseickel** [comment] 2022-01-23 16:28
This is a duplicate of #44 which is in progress.

The folder icon can be customized, see the help file at `:h Neo-tree-Configuration`

You just need to specify a custom renderer for directory:

```lua
 ...
  filesystem = {
    renderers = {
      directory = {
        {
          "icon",
          folder_closed = "",
          folder_open = "",
          padding = " ",
        },
        { "current_filter" },
        { "name" },
        {
          "clipboard",
          highlight = "NeoTreeDimText"
        },
        { "diagnostics", errors_only = true },
        --{ "git_status" },
      },
  ...
```

**Closed** 2022-01-23 16:29 UTC
Labels: duplicate

**Comment by nyngwang** [comment] 2022-01-23 16:47
@cseickel: I will expect that I don't need to provide fields I don't want to customize. But without the `{ 'name' }` option, the folder name did not get shown.

**Comment by cseickel** [comment] 2022-01-23 16:57
That wouldn't really make sense because it's not just about the configuration, it's just as much about which components you are using and in what order. I can't assume that you want the built-in `name` component if you didn't specify it. What if you created a custom name component and wanted to use that instead? What if you want other components in between icon and name? The only way this makes sense is if you specify the complete line to be rendered.

A lot of design decisions here take the side of "what is the most open ended and flexible" over what is the shortest path to one specific change.

**Comment by nyngwang** [comment] 2022-01-23 17:03
@cseickel: Okay, then I hope the length of code needed to just change the icons can be shortened in version 2.x!
