### ISSUE TITLE
:bd crashes nvim

### ISSUE THREAD

**Issue by TheButlah** [nvim-neo-tree/neo-tree.nvim#582] opened 2022-10-24 14:25 UTC
I opened an [issue](https://github.com/AstroNvim/AstroNvim/issues/1165) in AstroNvim, and was told to transfer it here instead. I would make a more minimally reproducible example that cuts out the rest of the astro plugins, but unfortunately I have no idea how to do that.

### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [x] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.4.2

### Neovim version (>= 0.8)

NVIM v0.8.0

### Operating system/version

macOS 12.6

### Describe the bug

`:bd` crashes `nvim`

### Steps to Reproduce

1. Run `nvim`
2. Open the file tree: `<SPACE>e` 
3. Edit a file: `:e foo.txt`
4. Edit another file: `:e bar.txt`
5. Close the current buffer: `:bd`

### Expected behavior

`:bd` should merely close the current buffer, not exit nvim completely

### Screenshots

https://user-images.githubusercontent.com/6969415/197542344-e0e53ac2-386e-4ec8-889e-b60eaa7ebf07.mov

### Additional Context

Return code:
```
❯ echo $?
0
```

**Comment by kay-adamof** [comment] 2022-10-25 12:25
Hi, @TheButlah 

Your issue may be occurred by the default behavior of Neovim, not caused by Neo-tree.

AstroNvim already serves a  keymap of closing a buffer by hitting "<space>c" so that you should use it.

See the details below:

- [famiu/bufdelete.nvim](https://github.com/famiu/bufdelete.nvim)
- [Plugin list used in Astro](https://github.com/famiu/bufdelete.nvim)
- [Default mappings of Astro(See, "close buffer"](https://github.com/famiu/bufdelete.nvim)

**Comment by nhat-vo** [comment] 2023-02-21 15:46
Closing as solved

**Closed by nhat-vo** 2023-02-21 15:46 UTC
