### ISSUE TITLE
The screen will blink when switching sources

### ISSUE THREAD

**Issue by NGPONG** [nvim-neo-tree/neo-tree.nvim#942] opened 2023-05-20 09:20 UTC
As the video shows, when I switch sources (using the prev/next_source command), the content of a buffer comes out of the screen uninterruptedly, but soon it disappears, and since the interval between the "appear" and "disappear" events is very short, what I see visually is that the screen flickers.

I can't provide any more useful information at this time because I don't have a clue yet. If there's anything to add, please alert me and I'll be sure to be the first to look! Thanks again for all your work!

Here is my environment:

```
wsl2 ubuntu-22.04

NVIM v0.10.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

Here is my attempted:

1. Disable all extraneous configurations and keep only the minimal configuration of the neo-tree

2. Try using other terminal emulators or gui's

Here is my minimal cfg:

```

  use {
    "nvim-neo-tree/neo-tree.nvim",
    branch = "v2.x",
    requires = {
      "nvim-lua/plenary.nvim",
      "nvim-tree/nvim-web-devicons",
      "MunifTanjim/nui.nvim",
      {
        's1n7ax/nvim-window-picker',
        tag = "v1.*",
        config = function()
          require'window-picker'.setup({
            autoselect_one = true,
            include_current = false,
            filter_rules = {
              bo = {
                filetype = { 'neo-tree', "neo-tree-popup", "notify" },
                buftype = { 'terminal', "quickfix" },
              },
            },
            other_win_hl_color = '#e35e4f',
          })
        end,
      }
    },
  }

vim.g.neo_tree_remove_legacy_commands = 1

vim.fn.sign_define("DiagnosticSignError", {text = " ", texthl = "DiagnosticSignError"})
vim.fn.sign_define("DiagnosticSignWarn", {text = " ", texthl = "DiagnosticSignWarn"})
vim.fn.sign_define("DiagnosticSignInfo", {text = " ", texthl = "DiagnosticSignInfo"})
vim.fn.sign_define("DiagnosticSignHint", {text = "", texthl = "DiagnosticSignHint"})

require("neo-tree").setup({
  use_default_mappings = false,
  window = {
    position = "left",
    width = 40,
    mapping_options = {
      noremap = true,
      nowait = true,
    },
    mappings = {
      ['<CR>'] = 'open_with_window_picker',
      ['>'] = 'prev_source',
      ['<'] = 'next_source',
    }
  }
}
```

https://github.com/nvim-neo-tree/neo-tree.nvim/assets/38415769/4a1d61e5-d63f-4948-b6ae-7a66e40159c7

**Comment by cseickel** [comment] 2023-05-20 16:14
The screen flicker when switching between sources has been a topic of discussion for a little while, it's a known issue that no one has resolved yet. This is a duplicate of #713.

See #752 for more information.

**Closed by cseickel** 2023-05-20 16:14 UTC
