### ISSUE TITLE
How to keep the neo-tree status within all tabs?

### ISSUE THREAD

**Issue by MasouShizuka** [nvim-neo-tree/neo-tree.nvim#886] opened 2023-04-20 12:33 UTC
The current situation is that each tab has its own state.
For example, neo-tree of tab A is open, and when a new file is opened to tab B, the neo-tree is closed.

How to keep the state of neo-tree global.
For example, after neo-tree of tab A is opened, other tabs are also opened when enter, and after neo-tree of other tabs are closed, tab A is also closed.

I looked at the documentation roughly, and it seems that there is no such option. If it already exists, please let me know.

**Comment by miversen33** [comment] 2023-04-20 12:42
I believe I understand what you are asking, though I am not able to replicate what I believe you are asking. 

To clarify, are you asking how to keep Neo-tree open when you open a node within it? For example, when you open a file in the filesystem source, you want Neo-tree to stay open?

And can you please provide your configuration so I can better get an idea of what settings you have set?

**Comment by MasouShizuka** [comment] 2023-04-20 13:20
https://user-images.githubusercontent.com/44764707/233377753-b5feaf79-0c42-40c0-9b4b-aa5e57f5ffca.mp4
For example, in the above video, open `neo-tree` from `main.py`, and use `t` to open `game.py`, the `neo-tree` of `game.py` is not opened.


https://user-images.githubusercontent.com/44764707/233378563-4801c986-85d0-47e7-ab18-c9ff4f071532.mp4
For example, in the second video, the `neo-tree` of `main.py` and `game.py` are both open, and after closing the `neo-tree` of `game.py`, go to `main.py` , `neo-tree` is still open.

Below is the minimal reproducible configuration.

```lua
vim.keymap.set("n", "<C-h>", "gt", { silent = true })
vim.keymap.set("n", "<C-l>", "gT", { silent = true })

local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        "git",
        "clone",
        "--filter=blob:none",
        "https://github.com/folke/lazy.nvim.git",
        "--branch=stable", -- latest stable release
        lazypath,
    })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup(
    {
        "nvim-neo-tree/neo-tree.nvim",
        branch = "v2.x",
        cmd = "Neotree",
        config = function(_, opts)
            -- If you want icons for diagnostic errors, you'll need to define them somewhere:
            vim.fn.sign_define("DiagnosticSignError", { text = " ", texthl = "DiagnosticSignError" })
            vim.fn.sign_define("DiagnosticSignWarn", { text = " ", texthl = "DiagnosticSignWarn" })
            vim.fn.sign_define("DiagnosticSignInfo", { text = " ", texthl = "DiagnosticSignInfo" })
            vim.fn.sign_define("DiagnosticSignHint", { text = "", texthl = "DiagnosticSignHint" })
            -- NOTE: this is changed from v1.x, which used the old style of highlight groups
            -- in the form "LspDiagnosticsSignWarning"
        end,
        deactivate = function()
            vim.cmd([[Neotree close]])
        end,
        dependencies = {
            "MunifTanjim/nui.nvim",
            "nvim-lua/plenary.nvim",
            "nvim-tree/nvim-web-devicons",
        },
        keys = {
            {
                [[<C-\>]],
                function()
                    require("neo-tree.command").execute({ toggle = true })
                end,
                mode = "n",
            },
        },
    }
)
```

**Comment by miversen33** [comment] 2023-04-20 13:44
Gotcha I was misunderstanding. So the issue is `open_tabnew` (the command bound to `t`) is closing Neo-tree after open. Just for giggles, if you use `Enter` instead of `t` to open, is that an acceptable workaround? Basically just `open` (which will open in a new tab anyway) as opposed to `open_tabnew`?

**Comment by MasouShizuka** [comment] 2023-04-20 13:56
If enter is used, neovim will open a buffer in the current tab.
I migrated from vscode, and I am not very used to the buffer of neovim.
So I basically only use t to edit multiple files.
At present, every time I am in a new tab, I have to reprocess the neo-tree, which is a little troublesome.

**Comment by miversen33** [comment] 2023-04-20 14:10
I'm tracking. I am not seeing anything in the available configuration for `pinning` Neo-tree open. I also am not super familiar with the file opening process within Neo-tree, so I will need to investigate this a bit. Alternatively, @cseickel  may have some quicker answers :)

**Comment by cseickel** [comment] 2023-04-20 17:32
I think there is a bit of a misunderstanding about what a tab is in (neo)vim. A tab is not an open file, it's a new window layout. It would not make sense for neo-tree to be open in a new tab because it was open in another tab.

That being said, other file explorers do have options to automatically copy their state to new tabs to make it appear like tabs are something they are not. I refuse to accommodate such things.

I think what you really want is a plugin that shows buffers as tabs, because you don't really want to use the tab system in vim. Here's an example: https://github.com/akinsho/bufferline.nvim

**Closed** 2023-05-15 21:29 UTC
Labels: question, how-to

**Comment by lougreenwood** [comment] 2023-11-09 08:46
I just wanted to add a +1 here.

I also use tabs, specifically to group together logically related files/buffers (route, controller, template in an SPA codebase, for example).

As I move between tabs I'm often in a mental mode where I expect the tree to be open, or rather I don't expect that changing between my workspaces should modify the layout of anything except the buffer splits and force my brain to have to re-evaluate the whole UI again and understand "did I hit the wrong key combo, maybe I changed the terminal tab rather than the vim tab, why does this look so different"... etc.

IMO this is compatible with the idea that tabs are "workspaces", it's just that I would like Neotree to allow me to have consistency between these workspaces with respect to the open state of the tree.
