### ISSUE TITLE
Closing current buffer with `bd` quits vim

### ISSUE THREAD

**Issue by paprikman** [nvim-neo-tree/neo-tree.nvim#364] opened 2022-05-31 02:58 UTC
When multiple buffers and the neo-tree are open, using `bd` command only leaves the neo-tree open and maximized, instead showing the next buffer. If the `close_if_last_window` setting is set, this results in quitting vim.
If the neo-tree was not open, `bd` works fine.

Tested with:

- neo-tree: v2.x, commit `a917174b38b065b5fc01c89709cfc31fbe6917db`
- NVIM v0.8.0-dev+181-ga2d4b862f
- LuaJIT 2.1.0-beta3

MWE configuration:
```vim
call plug#begin('~/.local/share/nvim/plugged')
  Plug 'nvim-lua/plenary.nvim'
  Plug 'MunifTanjim/nui.nvim'
  Plug 'nvim-neo-tree/neo-tree.nvim'
call plug#end()

nn <silent> <c-e> :NeoTreeFocusToggle<cr>

lua <<EOF
  require'neo-tree'.setup {
    close_if_last_window = true
  }
EOF
```

**Comment by cseickel** [comment] 2022-05-31 12:26
This sounds like it's working like it is supposed to. Please note that the feature is "close if last **window**", not "close if last **buffer**".

This seems to be a duplicate of #241.

If what you want is to close nvim if Neo-tree is the last **buffer**, then that is a simple task that can be handled with an autocmd and doesn't really require a plugin feature. This will work universally to close nvim when the last `listed` buffer is closed:

```
augroup CLOSE_IFLAST_BUFFER
    autocmd!
    autocmd BufDelete * silent! if len(getbufinfo({'buflisted':1})) == 0 | q | endif
augroup END
```

Neo-tree, and many other utility buffers are not `listed` so this works out well.

**Comment by paprikman** [comment] 2022-05-31 13:18
I totally understand what you're talking about, but this indeed feels wrong in terms of UX. I think I will just fork it and change the behaviour to my needs.
Thanks for your work.

**Closed** 2022-06-01 03:13 UTC
Labels: wontfix

**Comment by nyngwang** [comment] 2022-06-01 06:16
@paprikman Kindly introduce you to my plugin: https://github.com/nyngwang/NeoNoName.lua, which is designed with consideration of compatibility with neo-tree. I have been using it for months.
