### ISSUE TITLE
FEATURE: Show all the opened buffers without changing the root or CWD

### ISSUE THREAD

**Issue by lukepass** [nvim-neo-tree/neo-tree.nvim#1411] opened 2024-03-22 17:19 UTC
### Did you check the docs?

- [X] I have read all the docs.

### Is your feature request related to a problem? Please describe.

Hello, I was not able to achieve the current task:

`Open the list of **ALL** buffers (whether or not they are in the current working directory) without changing the CWD or the root node`

Thanks.

### Describe the solution you'd like.

I would like to be able to set the root of a window for that instance only.

### Describe alternatives you've considered.

I have tried this:

`:Neotree float buffers dir=/ reveal_force_cwd`

And it kinda works but then when I want to open the tree for xample with `:Neotree toggle` the root is automatically set to `/`.

**Comment by pysan3** [comment] 2024-03-22 17:28
Set `bind_to_cwd = false` in your buffers config. 

Also just go with `:Neotree (float) buffers dir=/` (float is optional). 

Also try `follow_current_file.enabled = true`.

**Comment by antonioparisi** [comment] 2024-03-26 22:42
+1

**Comment by cseickel** [comment] 2024-03-26 22:55
Closing this because it is a duplicate of #885.

**Closed by cseickel** 2024-03-26 22:55 UTC
Labels: enhancement
