### ISSUE TITLE
Overall slowness on windows

### ISSUE THREAD

**Issue by kishikaisei** [nvim-neo-tree/neo-tree.nvim#373] opened 2022-06-08 17:32 UTC
So I experience overall slowness of neo-tree. I am using the nightly build of neovim on windows.

https://user-images.githubusercontent.com/1894123/172680669-e2fe54e4-72a3-41ac-a7c8-3c0cd6f23327.mp4

**Comment by cseickel** [comment] 2022-06-10 19:39
I would usually start with looking at the git situation and file watchers if you are using those features. Can you post your config?

**Comment by kishikaisei** [comment] 2022-06-14 07:48
Yup, here it is, I hope it is legible enough:
https://gitlab.com/kishikaisei/nvim

**Comment by kishikaisei** [comment] 2022-06-15 09:42
> I would usually start with looking at the git situation and file watchers if you are using those features. Can you post your config?
The above repo is under SVN, and even if I `cd` to Desktop, and try to open it, it takes a while. But the bigger the project, the slower it gets (which is expected, but not to that extent).

**Comment by kishikaisei** [comment] 2022-06-15 18:37
Disabling diagnostics seems to help a bit, but still not snappy. (what does Diagnostics do?)
I kept git status as I use in many other repos.
For the troubleshooting, I got way too overwhelmed by the data...
https://gist.github.com/kishikaisei/ad4757c6fc0fb7db1e8cab79bfa01113

**Comment by cseickel** [comment] 2022-06-15 19:59
> Disabling diagnostics seems to improve slightly, but still not snappy. (what does Diagnostics do?)

Diagnostics is for LSP Diagnostics, meaning error, warning, info signs applied to your files whenever an LSP server reports them.



> I kept git status as I use in many other repos.

The point of disabling it is to identify what the cause of the slowdown is. Turn it off and let me know if that fixes it. If it does, you most likely have a `git` problem that is causing the status checks to run slowly.

Looking at the lkogs, it seems like this check for git ignored files is adding an extra second to the display:
```
[TRACE Wed Jun 15 20:30:17 2022] ...\packer\start\neo-tree.nvim/lua/neo-tree/git/ignored.lua:44: IGNORED: mark_ignore BEGIN...
[TRACE Wed Jun 15 20:30:17 2022] ...\packer\start\neo-tree.nvim/lua/neo-tree/git/ignored.lua:61: IGNORED: Running cmd:  { "git", "-C", "C:\\Users\\neil.messelmani\\AppData\\Local\\nvim", "check-ignore", "C:\\Users\\neil.messelmani\\AppData\\Local\\nvim\\lua" }
[TRACE Wed Jun 15 20:30:18 2022] ...\packer\start\neo-tree.nvim/lua/neo-tree/git/ignored.lua:61: IGNORED: Running cmd:  { "git", "-C", "C:\\Users\\neil.messelmani\\AppData\\Local\\nvim\\lua", "check-ignore", "C:\\Users\\neil.messelmani\\AppData\\Local\\nvim\\lua\\packer_compiled.lua", "C:\\Users\\neil.messelmani\\AppDa...
```

**Comment by kishikaisei** [comment] 2022-06-15 20:02
Disabled git, and in my config as CWD, it takes about a second to open the panel, same with expanding folders.

**Comment by cseickel** [comment] 2022-06-15 20:05
What about other folders, especially ones that are not withing your user profile?

**Comment by kishikaisei** [comment] 2022-06-15 20:10
Same, tried some folder in `D:` it is slow as well.

**Comment by cseickel** [comment] 2022-06-18 01:36
I just realized that disabling git does not actually affect the git ignored filter, try this settings and tell me if it changes anything:

```lua
    require("neo-tree").setup({
      filesystem = {
        filtered_items = {
          hide_gitignored = false,
        }
      }
    })
```

**Comment by kishikaisei** [comment] 2022-06-20 06:38
Didn't notice any difference :(

**Comment by cseickel** [comment] 2022-06-20 12:22
Do you get the same delay with nvim-tree?

**Comment by kishikaisei** [comment] 2022-06-20 18:29
Yes, even though this is the work computer which is quite beefy (i7-11700KF with 3080 Ti and 32gigs of ram)

**Comment by cseickel** [comment] 2022-06-20 18:39
Honestly, it's probably your anti-virus or some other security related bloat. That's precisely why I don't develop on the Windows computer that was provided to me by work. My advice is to get yourself a cheap linux computer that you can ssh into and work on that instead. If that's out of the question, use a VM or a docker container.

Personally, I use an older laptop with Arch Linux as my primary computer, and remote desktop into the super powerful (but horribly broken and bloated) brand new Windows PC that I was given only when I absolutely have to.

**Comment by Shougo** [comment] 2022-06-20 21:30
In my experience, Windows is really slow especially file operations.

**Comment by cseickel** [comment] 2022-06-24 00:03
Closing because I don't think this is a neo-tree problem.

**Closed by cseickel** 2022-06-24 00:03 UTC

**Comment by kishikaisei** [comment] 2022-06-25 11:58
I wanted to add that I tried [nerd-tree](https://github.com/preservim/nerdtree) and [fern](https://github.com/lambdalisue/fern.vim) and they are very snappy.

**Comment by cseickel** [comment] 2022-06-25 13:41
> I wanted to add that I tried [nerd-tree](https://github.com/preservim/nerdtree) and [fern](https://github.com/lambdalisue/fern.vim) and they are very snappy.

The difference is probably that nvim-tree and neo-tree use nvim's built-in libuv. I honestly have no idea how nerdtree and fern reads the filesystem, but it must be completely different because libuv is neovim only.

libuv is nice for a lot of things, but maybe it's slower on certain systems. I can't really debug this because I don't use neovim on Windows and I never had a problem when I did test Neo-tree on Windows.

I am happy to take a PR that addresses this if you or anyone else can find the issue.
